# Common source-tree entry point for out-of-tree builds.

REBSD_TOPSRC ?= $(abspath $(CURDIR)/$(REBSD_TOPSRC_REL))
REBSD_OBJMAKE = $(REBSD_TOPSRC)/tools/build/objmake.sh

REBSD_PROFILE_BOARD = $(if $(BOARD),$(BOARD),$(if $(TARGET_PLATFORM),$(TARGET_PLATFORM),default))
REBSD_DEFAULT_CPU = $(if $(filter n64 malta64,$(REBSD_PROFILE_BOARD)),vr4300,$(if $(filter malta maltael ci20,$(REBSD_PROFILE_BOARD)),mips32r2,default))
REBSD_DEFAULT_ENDIAN = $(if $(filter maltael ci20,$(REBSD_PROFILE_BOARD)),little,$(if $(filter n64 malta malta64,$(REBSD_PROFILE_BOARD)),big,default))
REBSD_DEFAULT_EXEC = $(if $(filter n64,$(REBSD_PROFILE_BOARD)),aout,$(if $(filter malta malta64 maltael ci20,$(REBSD_PROFILE_BOARD)),elf,default))
REBSD_PROFILE_KERNEL = $(if $(N64_KERNEL_COMPILER),$(N64_KERNEL_COMPILER),$(if $(MIPS_KERNEL_COMPILER),$(MIPS_KERNEL_COMPILER),gcc))
REBSD_PROFILE_USER = $(if $(N64_USERLAND_COMPILER),$(N64_USERLAND_COMPILER),$(if $(MIPS_ROOTFS_COMPILER),$(MIPS_ROOTFS_COMPILER),gcc))
REBSD_PROFILE_CPU = $(if $(N64_USERLAND_CPU),$(N64_USERLAND_CPU),$(if $(MIPS_ROOTFS_CPU),$(MIPS_ROOTFS_CPU),$(REBSD_DEFAULT_CPU)))
REBSD_PROFILE_FLOAT = $(if $(N64_USERLAND_FLOAT),$(N64_USERLAND_FLOAT),$(if $(MIPS_ROOTFS_FLOAT),$(MIPS_ROOTFS_FLOAT),hard))
REBSD_PROFILE_ENDIAN = $(if $(N64_USERLAND_ENDIAN),$(N64_USERLAND_ENDIAN),$(if $(MIPS_ROOTFS_ENDIAN),$(MIPS_ROOTFS_ENDIAN),$(REBSD_DEFAULT_ENDIAN)))
REBSD_PROFILE_EXEC = $(if $(N64_USERLAND_EXEC_FORMAT),$(N64_USERLAND_EXEC_FORMAT),$(if $(MIPS_ROOTFS_EXEC_FORMAT),$(MIPS_ROOTFS_EXEC_FORMAT),$(REBSD_DEFAULT_EXEC)))
BUILD_PROFILE ?= $(REBSD_PROFILE_BOARD)-k$(REBSD_PROFILE_KERNEL)-u$(REBSD_PROFILE_USER)-$(REBSD_PROFILE_CPU)-$(REBSD_PROFILE_FLOAT)-$(REBSD_PROFILE_ENDIAN)-$(REBSD_PROFILE_EXEC)
O ?= $(abspath $(REBSD_TOPSRC)/../$(notdir $(REBSD_TOPSRC))-build/$(BUILD_PROFILE))

.DEFAULT_GOAL := __obj_dispatch
.PHONY: __obj_dispatch $(MAKECMDGOALS)

__obj_dispatch:
	@REBSD_REAL_MAKE='$(MAKE)' \
	    $(REBSD_OBJMAKE) --top-source '$(REBSD_TOPSRC)' \
	    --top-object '$(O)' --source-dir '$(CURDIR)' \
	    $(if $(MAKECMDGOALS),$(MAKECMDGOALS),all)

$(MAKECMDGOALS): __obj_dispatch
	@:
