#
# Makefile template for shared MIPS ports.
#
MALTA_CPU_TUNE ?= 24kf
MIPS_ARCH ?= -EB -mips32 -mabi=32 -mtune=$(MALTA_CPU_TUNE)
MALTA_QEMU_RAM ?= 32M

include ../../../target-mips.mk

TOPSRC          = ../../..
S               = ../..
BOARD_SRC       = ../malta
MIPS_ROOTFS_KBYTES ?= 16384
MIPS_ROOTFS_SRC ?= $(TOPSRC)/sys/mips/n64/rootfs.stage
MIPS_ROOTFS_SRC_STAMP ?= $(MIPS_ROOTFS_SRC)/.userland
MIPS_ROOTFS_OVERLAY ?= $(TOPSRC)/sys/mips/malta/rootfs
MIPS_ROOTFS_COMMON_MANIFEST ?= $(TOPSRC)/sys/mips/rootfs.manifest
MIPS_ROOTFS_BOARD_MANIFEST ?= $(TOPSRC)/sys/mips/malta/rootfs.manifest
MIPS_ROOTFS_BUILD_MANIFEST = rootfs.generated.manifest
MIPS_ROOTFS_STAGE = rootfs.stage
MIPS_ROOTFS_STAMP = $(MIPS_ROOTFS_STAGE)/.stamp
MIPS_ROOTFS_COMMON_FILES = $(shell find $(TOPSRC)/sys/mips/rootfs \
                           -type f -o -type l 2>/dev/null)
MIPS_ROOTFS_OVERLAY_FILES = $(shell find $(MIPS_ROOTFS_OVERLAY) -type f -o -type l 2>/dev/null)
MIPS_COMMON_MACHINE_HEADERS = console cpu devmajors elf_machdep float fpu io \
                              layout limits machparam ramswap romdisk
MIPS_TRACE       ?= 0
FSUTIL          = $(TOPSRC)/tools/fsutil/fsutil
PCC_HOST_SMOKE_SCRIPT = $(TOPSRC)/sys/mips/n64/native/smoke-host-portablecc.sh
PCC_HOST_BUILD ?= /private/tmp/rebsd-pcc-build
PCC_HOST_PREFIX ?= /private/tmp/rebsd-pcc-install
PCC_HOST_AS     = $(TOPSRC)/sys/mips/n64/n64-native-tools/as
PCC_HOST_LD     = $(TOPSRC)/sys/mips/n64/n64-native-tools/ld
PCC_HOST_AR     = $(TOPSRC)/sys/mips/n64/n64-native-tools/ar
PCC_HOST_PCC    = $(PCC_HOST_PREFIX)/bin/mips-rebsd-pcc
PCC_REGRESS_SCRIPT = $(TOPSRC)/sys/mips/tools/pcc-regress.py
PCC_REGRESS_OUT ?= /private/tmp/rebsd-pcc-tests
PCC_REGRESS_MANIFEST ?= /private/tmp/rebsd-pcc-tests.manifest
PCC_REGRESS_LOG ?= /private/tmp/rebsd-pcc-runtime.log
LINPACK_SMOKE_SCRIPT = $(TOPSRC)/sys/mips/tools/linpack-smoke.py
LINPACK_SMOKE_SRC = $(TOPSRC)/sys/mips/rootfs/root/linpack.c
LINPACK_SMOKE_OUT ?= /private/tmp/rebsd-linpack-smoke
LINPACK_SMOKE_MANIFEST ?= /private/tmp/rebsd-linpack-smoke.manifest
LINPACK_SMOKE_LOG ?= /private/tmp/rebsd-linpack-smoke.log
LINPACK_SMOKE_ARRAY_SIZE ?= 120
LINPACK_SMOKE_MIN_SECONDS ?= 1
MALTA_RUN_COMMAND_SCRIPT = $(TOPSRC)/sys/mips/tools/malta-run-command.py
NATIVE_PCC_SMOKE_LOG ?= /private/tmp/rebsd-native-pcc-smoke.log

CPPFLAGS        = -I. -I$(TOPSRC)/include ${PARAM} -DKERNEL -DMIPS \
                  -DROMFS_ENABLED \
                  -DHW_MACHINE_NAME=\"mips\" \
                  -DHW_MODEL_NAME='"MIPS Malta 24Kf"'
ifneq ($(filter -DINET_ENABLED,$(PARAM)),)
CPPFLAGS        += -I$(TOPSRC)/include/sys -I$(TOPSRC)/sys \
                  -I$(TOPSRC)/sys/net \
                  -I$(TOPSRC)/sys/netinet -DINET -DSUPERVISOR
INET_CWARN      = -Wno-comment -Wno-endif-labels -Wno-implicit-int \
                  -Wno-implicit-function-declaration -Wno-parentheses \
                  -Wno-return-mismatch -Wno-return-type
endif
ifneq ($(filter -DUNIXDOMAIN_ENABLED,$(PARAM)),)
CPPFLAGS        += -DUNIXDOMAIN
endif
ifeq ($(MIPS_TRACE),1)
CPPFLAGS        += -DMIPS_TRACE
endif
CFLAGS          = -O2 -Wall -Werror -Wno-array-bounds -nostdinc \
                  $(CPPFLAGS) $(INET_CWARN) -MT $@ -MP -MD -MF .deps/$*.dep
VERS_CFLAGS     = -O2 -Wall -Werror -Wno-array-bounds -nostdinc $(CPPFLAGS)
ASFLAGS         = -x assembler-with-cpp -c $(CPPFLAGS) -MT $@ -MP -MD \
                  -MF .deps/$*.dep
FPU_ASFLAGS     = $(ASFLAGS)

COMPILE_C       = ${CC} ${CFLAGS} -c $<
COMPILE_S       = ${AS} ${ASFLAGS} $< -o $@
COMPILE_FPU_S   = ${AS} ${FPU_ASFLAGS} $< -o $@

%OBJS

%CFILES

SYSTEM_OBJ      = ${OBJS} ioconf.o rootfs.o
SYSTEM_DEP      = Makefile ioconf.c ../malta/malta.ld
SYSTEM_LD_HEAD  = printf '%s\n' 'const char version[] = "ReBSD for Malta: local build\n";' > vers.c; \
                  ${CC} ${VERS_CFLAGS} -MT vers.o -MP -MD -MF .deps/vers.dep -c vers.c -o vers.o; \
                  rm -f $@
SYSTEM_LD       = ${LD} -nostdlib -T ../malta/malta.ld ${SYSTEM_OBJ} vers.o -o $@
SYSTEM_LD_TAIL  = ${SIZE} $@; \
                  ${OBJDUMP} -d -S $@ > $(basename $@).dis; \
                  ${NM} -n $@ > $(basename $@).nm

all: unix malta-early.elf

kernel: unix

malta-early.o: ../malta/early_uart.S | .deps
	$(CC) $(ASFLAGS) $< -o $@

malta-early.elf: malta-early.o ../malta/malta.ld
	$(LD) -nostdlib -T ../malta/malta.ld malta-early.o -o $@
	$(SIZE) $@
	$(OBJDUMP) -d -S $@ > malta-early.dis

run-early: malta-early.elf
	qemu-system-mips -M malta -m $(MALTA_QEMU_RAM) -nographic -serial mon:stdio \
	    -no-reboot -kernel malta-early.elf

run: unix.elf
	qemu-system-mips -M malta -m $(MALTA_QEMU_RAM) -nographic -serial mon:stdio \
	    -no-reboot -kernel unix.elf

run-net: unix.elf
	qemu-system-mips -M malta -m $(MALTA_QEMU_RAM) -nographic -serial mon:stdio \
	    -no-reboot -kernel unix.elf \
	    -netdev user,id=net0,guestfwd=tcp:10.0.2.100:2323-cmd:/bin/cat \
	    -device ne2k_isa,netdev=net0,iobase=0x300,irq=9,mac=52:54:00:12:34:56

.PHONY: smoke-host-portablecc pcc-regress-compile pcc-regress-stage \
        pcc-regress-runtime pcc-regress-summary linpack-smoke-build \
        linpack-smoke-stage linpack-smoke-runtime \
        native-pcc-smoke-runtime FORCE
smoke-host-portablecc: $(MIPS_ROOTFS_STAMP) $(PCC_HOST_SMOKE_SCRIPT)
	sh $(PCC_HOST_SMOKE_SCRIPT) $(abspath $(TOPSRC)) \
	    $(abspath $(PCC_HOST_BUILD)) $(abspath $(PCC_HOST_PREFIX)) \
	    $(abspath $(MIPS_ROOTFS_STAGE)/usr/include) \
	    $(abspath $(MIPS_ROOTFS_STAGE)/usr/lib) \
	    $(abspath $(PCC_HOST_AS)) $(abspath $(PCC_HOST_LD))

pcc-regress-compile: smoke-host-portablecc $(PCC_REGRESS_SCRIPT)
	python3 $(PCC_REGRESS_SCRIPT) compile \
	    --pcc $(abspath $(PCC_HOST_PCC)) \
	    --rootfs $(abspath $(MIPS_ROOTFS_STAGE)) \
	    --out $(PCC_REGRESS_OUT) \
	    --ar $(abspath $(PCC_HOST_AR))

pcc-regress-stage: pcc-regress-compile $(MIPS_ROOTFS_BUILD_MANIFEST)
	python3 $(PCC_REGRESS_SCRIPT) stage \
	    --out $(PCC_REGRESS_OUT) \
	    --rootfs $(abspath $(MIPS_ROOTFS_STAGE)) \
	    --manifest $(abspath $(MIPS_ROOTFS_BUILD_MANIFEST)) \
	    --manifest-out $(PCC_REGRESS_MANIFEST)
	cp $(PCC_REGRESS_MANIFEST) $(MIPS_ROOTFS_BUILD_MANIFEST)

pcc-regress-runtime: pcc-regress-stage
	$(MAKE) unix.elf
	python3 $(PCC_REGRESS_SCRIPT) run \
	    --malta-dir $(abspath .) \
	    --kernel unix.elf \
	    --log $(PCC_REGRESS_LOG) \
	    --ram $(MALTA_QEMU_RAM)

pcc-regress-summary: $(PCC_REGRESS_SCRIPT)
	python3 $(PCC_REGRESS_SCRIPT) summarize \
	    --out $(PCC_REGRESS_OUT) \
	    --log $(PCC_REGRESS_LOG)

linpack-smoke-build: smoke-host-portablecc $(LINPACK_SMOKE_SCRIPT) \
    $(LINPACK_SMOKE_SRC)
	python3 $(LINPACK_SMOKE_SCRIPT) build \
	    --source $(abspath $(LINPACK_SMOKE_SRC)) \
	    --out $(LINPACK_SMOKE_OUT) \
	    --top $(abspath $(TOPSRC)) \
	    --rootfs $(abspath $(MIPS_ROOTFS_STAGE)) \
	    --gcc-wrapper $(abspath $(TOPSRC)/sys/mips/n64/native/n64-aout-cc.sh) \
	    --gcc-prefix $(MIPS_PREFIX) \
	    --as $(abspath $(PCC_HOST_AS)) \
	    --ld $(abspath $(PCC_HOST_LD)) \
	    --pcc $(abspath $(PCC_HOST_PCC))

linpack-smoke-stage: linpack-smoke-build $(MIPS_ROOTFS_BUILD_MANIFEST)
	python3 $(LINPACK_SMOKE_SCRIPT) stage \
	    --out $(LINPACK_SMOKE_OUT) \
	    --rootfs $(abspath $(MIPS_ROOTFS_STAGE)) \
	    --manifest $(abspath $(MIPS_ROOTFS_BUILD_MANIFEST)) \
	    --manifest-out $(LINPACK_SMOKE_MANIFEST)
	cp $(LINPACK_SMOKE_MANIFEST) $(MIPS_ROOTFS_BUILD_MANIFEST)

linpack-smoke-runtime: linpack-smoke-stage
	$(MAKE) unix.elf
	python3 $(LINPACK_SMOKE_SCRIPT) run \
	    --malta-dir $(abspath .) \
	    --kernel unix.elf \
	    --log $(LINPACK_SMOKE_LOG) \
	    --ram $(MALTA_QEMU_RAM) \
	    --array-size $(LINPACK_SMOKE_ARRAY_SIZE) \
	    --min-seconds $(LINPACK_SMOKE_MIN_SECONDS)

native-pcc-smoke-runtime: $(MIPS_ROOTFS_STAMP) $(MALTA_RUN_COMMAND_SCRIPT)
	$(MAKE) unix.elf
	python3 $(MALTA_RUN_COMMAND_SCRIPT) \
	    --malta-dir $(abspath .) \
	    --kernel unix.elf \
	    --log $(NATIVE_PCC_SMOKE_LOG) \
	    --ram $(MALTA_QEMU_RAM) \
	    --command '/root/native-pcc-smoke.sh; echo NATIVE_PCC_SMOKE_RC:$$?' \
	    --expect "NATIVE_PCC_SMOKE_RC:0"

FORCE:

$(MIPS_ROOTFS_SRC_STAMP): FORCE
	$(MAKE) -C $(TOPSRC)/sys/mips/n64 rootfs.stage/.userland

$(MIPS_ROOTFS_STAMP): $(MIPS_ROOTFS_SRC_STAMP) $(MIPS_ROOTFS_OVERLAY_FILES)
	rm -rf $(MIPS_ROOTFS_STAGE)
	mkdir -p $(MIPS_ROOTFS_STAGE)
	cp -pR $(MIPS_ROOTFS_SRC)/. $(MIPS_ROOTFS_STAGE)/
	cp -pR $(MIPS_ROOTFS_OVERLAY)/. $(MIPS_ROOTFS_STAGE)/
	rm -rf $(MIPS_ROOTFS_STAGE)/usr/include/machine
	mkdir -p $(MIPS_ROOTFS_STAGE)/usr/include/machine
	for header in $(MIPS_COMMON_MACHINE_HEADERS); do \
	    cp -p $(TOPSRC)/sys/mips/$$header.h \
	        $(MIPS_ROOTFS_STAGE)/usr/include/machine/$$header.h; \
	done
	cp -p $(TOPSRC)/sys/mips/include/machine/types.h \
	    $(MIPS_ROOTFS_STAGE)/usr/include/machine/types.h
	touch $@

$(MIPS_ROOTFS_BUILD_MANIFEST): $(MIPS_ROOTFS_COMMON_MANIFEST) $(MIPS_ROOTFS_BOARD_MANIFEST) $(MIPS_ROOTFS_STAMP)
	cp $(MIPS_ROOTFS_COMMON_MANIFEST) $@
	find $(MIPS_ROOTFS_STAGE)/usr/include -type d | sort | while read path; do \
	    rel=$${path#$(MIPS_ROOTFS_STAGE)}; \
	    printf '\ndir %s\n' "$$rel" >> $@; \
	done
	find $(MIPS_ROOTFS_STAGE)/usr/include -type f ! -name '.gitignore' \
	    ! -name Makefile ! -name Makefile.install | sort | while read path; do \
	    rel=$${path#$(MIPS_ROOTFS_STAGE)}; \
	    printf '\nfile %s\n' "$$rel" >> $@; \
	done
	find $(MIPS_ROOTFS_STAGE)/usr/include -maxdepth 1 -type l ! -name pic32 | \
	    sort | while read path; do \
	    rel=$${path#$(MIPS_ROOTFS_STAGE)}; \
	    target=$$(readlink "$$path"); \
	    printf '\nsymlink %s\ntarget %s\n' "$$rel" "$$target" >> $@; \
	done
	cat $(MIPS_ROOTFS_BOARD_MANIFEST) >> $@

rootfs.img: $(FSUTIL) $(MIPS_ROOTFS_STAMP) $(MIPS_ROOTFS_BUILD_MANIFEST)
	rm -f $@
	$(FSUTIL) --new --endian=big --size=$(MIPS_ROOTFS_KBYTES) \
	    --manifest=$(MIPS_ROOTFS_BUILD_MANIFEST) $@ $(MIPS_ROOTFS_STAGE)
	$(FSUTIL) --check $@

rootfs.o: rootfs.img
	$(LD) -r -b binary -o $@ rootfs.img
	$(OBJCOPY) --rename-section .data=.romdisk,alloc,load,readonly,data,contents $@

ioconf.o: ioconf.c ${SYSTEM_DEP} | machine sys .deps
	${COMPILE_C}

${SYSTEM_OBJ} swapunix.o: | machine sys .deps

$(FSUTIL):
	$(MAKE) -C $(TOPSRC)/tools/fsutil

reconfig ioconf.c swapunix.c: Config ../../../tools/kconfig/kconfig | machine sys
	../../../tools/kconfig/kconfig Config

machine:
	ln -s .. $@

sys:
	ln -s ../../include $@

clean clean-all:
	rm -rf *.o *.elf *.bin *.img *.dis *.nm a.out .deps machine sys \
	    vers.c rootfs.stage rootfs.generated.manifest

.deps:
	mkdir -p .deps

%LOAD

%RULES

-include .deps/*.dep
