#
# Makefile template for RetroBSD on Nintendo 64.
#
include ../../../target-n64.mk

TOPSRC          = ../../..
S               = ../..

N64_KERNEL_ARCH = -EB -march=vr4300 -mtune=vr4300 -mips3 -mabi=32
N64_KERNEL_BASE = -G0 -mno-abicalls -fno-pic -ffreestanding -fno-builtin \
                  -fomit-frame-pointer
N64_KERNEL_CODE = $(N64_KERNEL_BASE) -msoft-float
N64_FPU_CODE    = $(N64_KERNEL_BASE) -mhard-float
N64_TRACE       ?= 0
N64_ROOTFS_KBYTES ?= 512
N64_ROOTFS_DIR  ?= $(TOPSRC)/sys/n64/rootfs
N64_ROOTFS_MANIFEST ?= $(TOPSRC)/sys/n64/rootfs.manifest
N64_ROOTFS_DEVNODES = rootfs.devnodes.manifest
N64_ROOTFS_BUILD_MANIFEST = rootfs.generated.manifest
N64_ROOTFS_STAGE = rootfs.stage
N64_ROOTFS_FILES = $(shell find $(N64_ROOTFS_DIR) -type f 2>/dev/null)
N64_DEVNODES_AWK = $(TOPSRC)/sys/n64/devnodes.awk
N64_DEVNODES_SRCS = $(N64_DEVNODES_AWK) $(TOPSRC)/sys/n64/romdisk.h \
                    $(TOPSRC)/sys/n64/ramswap.h $(TOPSRC)/sys/include/conf.h
N64_CONS_MAJOR = $(patsubst -DCONS_MAJOR=%,%,$(filter -DCONS_MAJOR=%,$(PARAM)))
N64_CONS_MINOR = $(patsubst -DCONS_MINOR=%,%,$(filter -DCONS_MINOR=%,$(PARAM)))
N64_CRT0_SRCS = $(shell find $(TOPSRC)/src/startup-mips -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_LIBC_SRCS = $(shell find $(TOPSRC)/src/libc -type f \( -name '*.[chS]' -o -name '*.inc' -o -name Makefile \) 2>/dev/null)
N64_SH_SRCS = $(shell find $(TOPSRC)/src/cmd/sh -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_LS_SRCS = $(shell find $(TOPSRC)/src/cmd/ls -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_USER_INIT = n64-init
N64_USER_SH = $(TOPSRC)/src/cmd/sh/sh
N64_USER_LS = $(TOPSRC)/src/cmd/ls/ls
N64_USERLAND = $(N64_USER_SH) $(N64_USER_LS)
N64_STAGE0_CONSOLE_OBJS = $(if $(filter n64cart_uart.o,$(OBJS)),stage0_n64cart_uart.o,stage0_console_null.o)
N64_STAGE0_OBJS = stage0.o stage0_loader.o $(N64_STAGE0_CONSOLE_OBJS)
N64_PREFLIGHT_CONSOLE_OBJS = $(filter n64cart_uart.o,$(OBJS))
N64_PREFLIGHT_OBJS = startup.o $(N64_PREFLIGHT_CONSOLE_OBJS) \
                     rompak.o memory.o preflight.o

CC              = $(N64_PREFIX)gcc $(N64_KERNEL_ARCH) $(N64_KERNEL_CODE)
AS              = $(N64_PREFIX)gcc $(N64_KERNEL_ARCH) $(N64_KERNEL_CODE)
ASFPU           = $(N64_PREFIX)gcc $(N64_KERNEL_ARCH) $(N64_FPU_CODE)
LD              = $(N64_PREFIX)ld -m elf32ebmip
OBJDUMP         = $(N64_PREFIX)objdump
SIZE            = $(N64_PREFIX)size
STRIP           = $(N64_PREFIX)strip
NM              = $(N64_PREFIX)nm
N64_TOOL        = $(N64_TOOLCHAIN)/bin/n64tool
FSUTIL          = $(TOPSRC)/tools/fsutil/fsutil
ELF2AOUT        = $(TOPSRC)/tools/elf2aout/elf2aout
ELF2AOUT_SRCS   = $(TOPSRC)/tools/elf2aout/Makefile \
                  $(TOPSRC)/tools/elf2aout/elf2aout.c

DEPFLAGS        = -MT $@ -MP -MD -MF .deps/$*.dep
CPPFLAGS        = -I. -I$(TOPSRC)/include ${PARAM} -DKERNEL -DN64
ifeq ($(N64_TRACE),1)
CPPFLAGS        += -DN64_TRACE
endif
DEFS            = $(CPPFLAGS) $(DEPFLAGS)
CFLAGS          = -O2 -Wall -Werror -Wno-array-bounds -nostdinc $(DEFS)
VERS_CFLAGS     = -O2 -Wall -Werror -Wno-array-bounds -nostdinc $(CPPFLAGS)
ASFLAGS         = -x assembler-with-cpp -c $(DEFS)
FPU_ASFLAGS     = -x assembler-with-cpp -c $(DEFS)
STAGE0_CFLAGS   = $(N64_KERNEL_ARCH) $(N64_KERNEL_BASE) -msoft-float \
                  -ffreestanding -fno-builtin -fno-stack-protector \
                  -fno-pie -Wall -Wextra -Werror -O2 -MMD -MP $(PARAM)
STAGE0_ASFLAGS  = $(N64_KERNEL_ARCH) $(N64_KERNEL_BASE) -msoft-float \
                  -x assembler-with-cpp -MMD -MP -c $(PARAM)

COMPILE_C       = ${CC} ${CFLAGS} -c $<
COMPILE_S       = ${AS} ${ASFLAGS} $< -o $@
COMPILE_FPU_S   = ${ASFPU} ${FPU_ASFLAGS} $< -o $@

%OBJS

%CFILES

SYSTEM_OBJ      = startup.o ${OBJS} ioconf.o
SYSTEM_DEP      = Makefile ioconf.c
SYSTEM_LD_HEAD  = printf '%s\n' 'const char version[] = "2.11 BSD Unix for N64: local build\n";' > vers.c; \
                  ${CC} ${VERS_CFLAGS} -MT vers.o -MP -MD -MF .deps/vers.dep -c vers.c -o vers.o; \
                  rm -f $@
SYSTEM_LD       = ${LD} -nostdlib -T ../n64.ld ${SYSTEM_OBJ} vers.o -o $@
SYSTEM_LD_TAIL  = ${SIZE} $@; \
                  ${OBJDUMP} -d -S $@ > $(basename $@).dis; \
                  ${NM} -n $@ > $(basename $@).nm

all: unix kernel.z64 preflight.z64

%LOAD

preflight: $(N64_PREFLIGHT_OBJS)
	$(SIZE) $(N64_PREFLIGHT_OBJS)

preflight.elf: $(N64_PREFLIGHT_OBJS) ../n64.ld
	$(LD) -nostdlib -T ../n64.ld $(N64_PREFLIGHT_OBJS) -o $@
	$(SIZE) $@
	$(OBJDUMP) -d -S $@ > preflight.dis

stage0.o: ../stage0.S | .deps
	$(N64_PREFIX)gcc $(STAGE0_ASFLAGS) $< -o $@

stage0_loader.o: ../stage0_loader.c | .deps
	$(N64_PREFIX)gcc $(STAGE0_CFLAGS) -c $< -o $@

stage0_console_null.o: ../stage0_console_null.c ../stage0_console.h | .deps
	$(N64_PREFIX)gcc $(STAGE0_CFLAGS) -c $< -o $@

stage0_n64cart_uart.o: ../stage0_n64cart_uart.c ../stage0_console.h ../n64cart_uart.h | .deps
	$(N64_PREFIX)gcc $(STAGE0_CFLAGS) -c $< -o $@

stage0_kernel_blob.o: ../stage0_kernel_blob.S preflight.elf | .deps
	$(N64_PREFIX)gcc $(STAGE0_ASFLAGS) -DN64_KERNEL_ELF=\"$(abspath preflight.elf)\" $< -o $@

kernel_stage0_kernel_blob.o: ../stage0_kernel_blob.S unix.elf | .deps
	$(N64_PREFIX)gcc $(STAGE0_ASFLAGS) -DN64_KERNEL_ELF=\"$(abspath unix.elf)\" $< -o $@

stage0.elf: $(N64_STAGE0_OBJS) stage0_kernel_blob.o ../stage0_linker.ld
	$(LD) -T ../stage0_linker.ld -nostdlib -o $@ $(N64_STAGE0_OBJS) stage0_kernel_blob.o

kernel_stage0.elf: $(N64_STAGE0_OBJS) kernel_stage0_kernel_blob.o ../stage0_linker.ld
	$(LD) -T ../stage0_linker.ld -nostdlib -o $@ $(N64_STAGE0_OBJS) kernel_stage0_kernel_blob.o

stage0.stripped.elf: stage0.elf
	$(STRIP) -s -o $@ $<

kernel_stage0.stripped.elf: kernel_stage0.elf
	$(STRIP) -s -o $@ $<

$(N64_ROOTFS_DEVNODES): $(N64_DEVNODES_SRCS) Makefile
	awk -v cons_major="$(N64_CONS_MAJOR)" -v cons_minor="$(N64_CONS_MINOR)" -f $(N64_DEVNODES_AWK) $(TOPSRC)/sys/n64/romdisk.h $(TOPSRC)/sys/n64/ramswap.h $(TOPSRC)/sys/include/conf.h > $@

$(N64_ROOTFS_BUILD_MANIFEST): $(N64_ROOTFS_MANIFEST) $(N64_ROOTFS_DEVNODES)
	cp $(N64_ROOTFS_MANIFEST) $@
	cat $(N64_ROOTFS_DEVNODES) >> $@

rootfs.img: $(FSUTIL) $(N64_ROOTFS_BUILD_MANIFEST) $(N64_ROOTFS_FILES) $(N64_USER_INIT) $(N64_USERLAND)
	rm -rf $(N64_ROOTFS_STAGE)
	mkdir -p $(N64_ROOTFS_STAGE)
	cp -R $(N64_ROOTFS_DIR)/. $(N64_ROOTFS_STAGE)/
	mkdir -p $(N64_ROOTFS_STAGE)/sbin
	cp $(N64_USER_INIT) $(N64_ROOTFS_STAGE)/sbin/init
	mkdir -p $(N64_ROOTFS_STAGE)/bin
	cp $(N64_USER_SH) $(N64_ROOTFS_STAGE)/bin/sh
	cp $(N64_USER_LS) $(N64_ROOTFS_STAGE)/bin/ls
	rm -f $@
	$(FSUTIL) --new --endian=big --size=$(N64_ROOTFS_KBYTES) --manifest=$(N64_ROOTFS_BUILD_MANIFEST) $@ $(N64_ROOTFS_STAGE)
	$(FSUTIL) --check $@

n64-init.o: ../user/init.S ../user/user.ld ${SYSTEM_DEP} | machine sys .deps
	${COMPILE_FPU_S}

n64-init.elf: n64-init.o ../user/user.ld
	$(LD) -nostdlib -T ../user/user.ld -o $@ n64-init.o
	$(SIZE) $@

n64-init: n64-init.elf $(ELF2AOUT)
	$(ELF2AOUT) $< $@

$(TOPSRC)/src/crt0.o: $(N64_CRT0_SRCS)
	$(MAKE) -C $(TOPSRC)/src/startup-mips TARGET_PLATFORM=n64

$(TOPSRC)/src/libc.a: $(TOPSRC)/src/crt0.o $(N64_LIBC_SRCS)
	$(MAKE) -C $(TOPSRC)/src/libc TARGET_PLATFORM=n64

$(N64_USER_SH): $(TOPSRC)/src/libc.a $(N64_SH_SRCS)
	$(MAKE) -B -C $(TOPSRC)/src/cmd/sh TARGET_PLATFORM=n64

$(N64_USER_LS): $(TOPSRC)/src/libc.a $(N64_LS_SRCS)
	$(MAKE) -B -C $(TOPSRC)/src/cmd/ls TARGET_PLATFORM=n64

$(FSUTIL):
	$(MAKE) -C $(TOPSRC)/tools/fsutil

$(ELF2AOUT): $(ELF2AOUT_SRCS)
	$(MAKE) -C $(TOPSRC)/tools/elf2aout

preflight.z64: stage0.stripped.elf rootfs.img
	$(N64_TOOL) --toc --title "RETROBSD N64" --output $@ --align 256 stage0.stripped.elf --align 1024 rootfs.img

kernel.z64: kernel_stage0.stripped.elf rootfs.img
	$(N64_TOOL) --toc --title "RETROBSD N64" --output $@ --align 256 kernel_stage0.stripped.elf --align 1024 rootfs.img

preflight.o: ../preflight.c ${SYSTEM_DEP}
	${COMPILE_C}

startup.o: ../startup.S ${SYSTEM_DEP}
	${COMPILE_S}

ioconf.o: ioconf.c ${SYSTEM_DEP}
	${COMPILE_C}

${SYSTEM_OBJ} swapunix.o preflight.o: | machine sys .deps

clean:
	rm -rf *.o *.elf *.bin *.img *.dis *.nm *.z64 *.d a.out n64-init \
	    .deps machine sys $(N64_ROOTFS_STAGE) $(N64_ROOTFS_DEVNODES) \
	    $(N64_ROOTFS_BUILD_MANIFEST)

clean-all: clean
	rm -f Makefile ioconf.c swap*.c vers.c

reconfig ioconf.c swapunix.c: Config ../../../tools/kconfig/kconfig | machine sys
	../../../tools/kconfig/kconfig Config
	$(MAKE) clean

machine:
	ln -s .. $@

sys:
	ln -s ../../include $@

.deps:
	mkdir .deps

%RULES

-include .deps/*.dep
