#
# Makefile template for RetroBSD on Nintendo 64.
#
include ../../../target-n64.mk

TOPSRC          = ../../..
S               = ../..

N64_KERNEL_ARCH = -EB -march=vr4300 -mtune=vr4300 -mips3 -mabi=32
N64_KERNEL_BASE = -G0 -mno-abicalls -fno-pic -ffreestanding -fno-builtin \
                  -fomit-frame-pointer
N64_KERNEL_CODE = $(N64_KERNEL_BASE) -msoft-float
N64_FPU_CODE    = $(N64_KERNEL_BASE) -mhard-float
N64_TRACE       ?= 0
N64_ROOTFS_KBYTES ?= 4096
N64_ROOTFS_DIR  ?= $(TOPSRC)/sys/n64/rootfs
N64_ROOTFS_MANIFEST ?= $(TOPSRC)/sys/n64/rootfs.manifest
N64_ROOTFS_DEVNODES = rootfs.devnodes.manifest
N64_ROOTFS_BUILD_MANIFEST = rootfs.generated.manifest
N64_ROOTFS_STAGE = rootfs.stage
N64_ROOTFS_BASE_STAMP = $(N64_ROOTFS_STAGE)/.base
N64_ROOTFS_USER_STAMP = $(N64_ROOTFS_STAGE)/.userland
N64_ROOTFS_WHATIS = $(N64_ROOTFS_STAGE)/share/man/whatis
N64_ROOTFS_FILES = $(shell find $(N64_ROOTFS_DIR) -type f 2>/dev/null)
N64_ROOTFS_DIRS = $(shell find $(N64_ROOTFS_DIR) -type d 2>/dev/null)
N64_TERMCAP = $(TOPSRC)/src/libtermlib/termcap/termcap.small
N64_MAKEWHATIS_SED = $(TOPSRC)/src/man/makewhatis.sed
N64_DEVNODES_AWK = $(TOPSRC)/sys/n64/devnodes.awk
N64_DEVNODES_SRCS = $(N64_DEVNODES_AWK) $(TOPSRC)/sys/n64/romdisk.h \
                    $(TOPSRC)/sys/n64/ramswap.h \
                    $(TOPSRC)/sys/n64/devmajors.h \
                    $(TOPSRC)/sys/include/conf.h \
                    $(TOPSRC)/sys/include/pty.h
N64_CONS_MAJOR = $(patsubst -DCONS_MAJOR=%,%,$(filter -DCONS_MAJOR=%,$(PARAM)))
N64_CONS_MINOR = $(patsubst -DCONS_MINOR=%,%,$(filter -DCONS_MINOR=%,$(PARAM)))
N64_PTY_ENABLED = $(filter -DPTY_ENABLED,$(PARAM))
N64_PTY_NUNITS = $(patsubst -DPTY_NUNITS=%,%,$(filter -DPTY_NUNITS=%,$(PARAM)))
N64_CRT0_SRCS = $(shell find $(TOPSRC)/src/startup-mips -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_LIBC_SRCS = $(shell find $(TOPSRC)/src/libc -type f \( -name '*.[chS]' -o -name '*.inc' -o -name Makefile \) 2>/dev/null)
N64_LIBUTIL_SRCS = $(shell find $(TOPSRC)/src/libutil -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_SRC_LIBS = startup-mips libc libutil libtermlib
N64_SRC_SUBDIRS = cmd
N64_CMD_NONE = __n64_none__
N64_CMD_SUBDIRS = deco env fbset fsck getty hostname id init login ls man more \
                  mkfs mount n64input ptytest reboot rgbled sh smux stty test \
                  umount uname chown
N64_CMD_STDS = cat chmod cp echo kill mkdir mv pwd rm rmdir sleep
N64_CMD_SCRIPTS = $(N64_CMD_NONE)
N64_CMD_EXTRA_SUBDIRS = deco fbset n64input ptytest rgbled
N64_USER_SRCS = $(TOPSRC)/src/Makefile $(TOPSRC)/src/cmd/Makefile \
                $(shell find $(TOPSRC)/src/cmd -maxdepth 3 -type f \( -name '*.[chSy]' -o -name '*.[0-9]' -o -name '*.sh' -o -name Makefile \) 2>/dev/null)
N64_USERLAND_STAMP = n64-userland.stamp
N64_SRC_MAKE = GROFF_NO_SGR=1 $(MAKE) -C $(TOPSRC)/src TARGET_PLATFORM=n64 \
               N64_USER_LDSCRIPT=$(abspath $(N64_USER_LDSCRIPT)) \
               DESTDIR=$(abspath $(N64_ROOTFS_STAGE)) \
               SRC_ONLY_LIBS="$(N64_SRC_LIBS)" \
               SRC_ONLY_SUBDIR="$(N64_SRC_SUBDIRS)" \
               CMD_ONLY_SUBDIR="$(N64_CMD_SUBDIRS)" \
               CMD_ONLY_STD="$(N64_CMD_STDS)" \
               CMD_ONLY_SCRIPT="$(N64_CMD_SCRIPTS)" \
               CMD_ONLY_NSTD="$(N64_CMD_NONE)" \
               CMD_ONLY_SETUID="$(N64_CMD_NONE)" \
               CMD_ONLY_OPERATOR="$(N64_CMD_NONE)" \
               CMD_ONLY_KMEM="$(N64_CMD_NONE)" \
               CMD_ONLY_TTY="$(N64_CMD_NONE)" \
               CMD_EXTRA_SUBDIR="$(N64_CMD_EXTRA_SUBDIRS)" \
               SMUX_SUBDIRS=retro \
               CMD_BUILD_STRIP=
N64_STAGE0_CONSOLE_OBJS = $(if $(filter n64cart_uart.o,$(OBJS)),stage0_n64cart_uart.o,stage0_console_null.o)
N64_STAGE0_OBJS = stage0.o stage0_loader.o $(N64_STAGE0_CONSOLE_OBJS)
N64_PREFLIGHT_CONSOLE_OBJS = $(if $(filter n64cart_uart.o,$(OBJS)),n64cart_uart.o,console_null.o)
N64_PREFLIGHT_OBJS = startup.o $(N64_PREFLIGHT_CONSOLE_OBJS) \
                     rompak.o memory.o preflight.o
N64_KERNEL_LDSCRIPT = n64.ld
N64_USER_LDSCRIPT = n64-user.ld

CC              = $(N64_PREFIX)gcc $(N64_KERNEL_ARCH) $(N64_KERNEL_CODE)
AS              = $(N64_PREFIX)gcc $(N64_KERNEL_ARCH) $(N64_KERNEL_CODE)
ASFPU           = $(N64_PREFIX)gcc $(N64_KERNEL_ARCH) $(N64_FPU_CODE)
LD              = $(N64_PREFIX)ld -m elf32ebmip
OBJDUMP         = $(N64_PREFIX)objdump
SIZE            = $(N64_PREFIX)size
STRIP           = $(N64_PREFIX)strip
NM              = $(N64_PREFIX)nm
N64_TOOL        = $(N64_TOOLCHAIN)/bin/n64tool
FSUTIL          = $(TOPSRC)/tools/fsutil/fsutil
ELF2AOUT        = $(TOPSRC)/tools/elf2aout/elf2aout
ELF2AOUT_SRCS   = $(TOPSRC)/tools/elf2aout/Makefile \
                  $(TOPSRC)/tools/elf2aout/elf2aout.c

DEPFLAGS        = -MT $@ -MP -MD -MF .deps/$*.dep
CPPFLAGS        = -I. -I$(TOPSRC)/include ${PARAM} -DKERNEL -DN64 \
                  -DHW_MACHINE_NAME=\"mips\" \
                  -DHW_MODEL_NAME='"NEC VR4300"'
ifeq ($(N64_TRACE),1)
CPPFLAGS        += -DN64_TRACE
endif
DEFS            = $(CPPFLAGS) $(DEPFLAGS)
CFLAGS          = -O2 -Wall -Werror -Wno-array-bounds -nostdinc $(DEFS)
VERS_CFLAGS     = -O2 -Wall -Werror -Wno-array-bounds -nostdinc $(CPPFLAGS)
ASFLAGS         = -x assembler-with-cpp -c $(DEFS)
FPU_ASFLAGS     = -x assembler-with-cpp -c $(DEFS)
STAGE0_CFLAGS   = $(N64_KERNEL_ARCH) $(N64_KERNEL_BASE) -msoft-float \
                  -ffreestanding -fno-builtin -fno-stack-protector \
                  -fno-pie -Wall -Wextra -Werror -O2 -MMD -MP $(PARAM)
STAGE0_ASFLAGS  = $(N64_KERNEL_ARCH) $(N64_KERNEL_BASE) -msoft-float \
                  -x assembler-with-cpp -MMD -MP -c $(PARAM)

COMPILE_C       = ${CC} ${CFLAGS} -c $<
COMPILE_S       = ${AS} ${ASFLAGS} $< -o $@
COMPILE_FPU_S   = ${ASFPU} ${FPU_ASFLAGS} $< -o $@

%OBJS

%CFILES

SYSTEM_OBJ      = startup.o ${OBJS} ioconf.o
SYSTEM_DEP      = Makefile ioconf.c $(N64_KERNEL_LDSCRIPT)
SYSTEM_LD_HEAD  = printf '%s\n' 'const char version[] = "2.11 BSD Unix for N64: local build\n";' > vers.c; \
                  ${CC} ${VERS_CFLAGS} -MT vers.o -MP -MD -MF .deps/vers.dep -c vers.c -o vers.o; \
                  rm -f $@
SYSTEM_LD       = ${LD} -nostdlib -T $(N64_KERNEL_LDSCRIPT) ${SYSTEM_OBJ} vers.o -o $@
SYSTEM_LD_TAIL  = ${SIZE} $@; \
                  ${OBJDUMP} -d -S $@ > $(basename $@).dis; \
                  ${NM} -n $@ > $(basename $@).nm

all: unix kernel.z64 preflight.z64

%LOAD

preflight: $(N64_PREFLIGHT_OBJS)
	$(SIZE) $(N64_PREFLIGHT_OBJS)

$(N64_KERNEL_LDSCRIPT): ../n64.ld ../layout.h
	$(N64_PREFIX)gcc -E -P -undef -x c $< -o $@

$(N64_USER_LDSCRIPT): ../user/user.ld.S ../layout.h
	$(N64_PREFIX)gcc -E -P -undef -x c $< -o $@

preflight.elf: $(N64_PREFLIGHT_OBJS) $(N64_KERNEL_LDSCRIPT)
	$(LD) -nostdlib -T $(N64_KERNEL_LDSCRIPT) $(N64_PREFLIGHT_OBJS) -o $@
	$(SIZE) $@
	$(OBJDUMP) -d -S $@ > preflight.dis

stage0.o: ../stage0.S | .deps
	$(N64_PREFIX)gcc $(STAGE0_ASFLAGS) $< -o $@

stage0_loader.o: ../stage0_loader.c | .deps
	$(N64_PREFIX)gcc $(STAGE0_CFLAGS) -c $< -o $@

stage0_console_null.o: ../stage0_console_null.c ../stage0_console.h | .deps
	$(N64_PREFIX)gcc $(STAGE0_CFLAGS) -c $< -o $@

stage0_n64cart_uart.o: ../stage0_n64cart_uart.c ../stage0_console.h ../n64cart_uart.h | .deps
	$(N64_PREFIX)gcc $(STAGE0_CFLAGS) -c $< -o $@

stage0_kernel_blob.o: ../stage0_kernel_blob.S preflight.elf | .deps
	$(N64_PREFIX)gcc $(STAGE0_ASFLAGS) -DN64_KERNEL_ELF=\"$(abspath preflight.elf)\" $< -o $@

kernel_stage0_kernel_blob.o: ../stage0_kernel_blob.S unix.elf | .deps
	$(N64_PREFIX)gcc $(STAGE0_ASFLAGS) -DN64_KERNEL_ELF=\"$(abspath unix.elf)\" $< -o $@

stage0.elf: $(N64_STAGE0_OBJS) stage0_kernel_blob.o ../stage0_linker.ld
	$(LD) -T ../stage0_linker.ld -nostdlib -o $@ $(N64_STAGE0_OBJS) stage0_kernel_blob.o

kernel_stage0.elf: $(N64_STAGE0_OBJS) kernel_stage0_kernel_blob.o ../stage0_linker.ld
	$(LD) -T ../stage0_linker.ld -nostdlib -o $@ $(N64_STAGE0_OBJS) kernel_stage0_kernel_blob.o

stage0.stripped.elf: stage0.elf
	$(STRIP) -s -o $@ $<

kernel_stage0.stripped.elf: kernel_stage0.elf
	$(STRIP) -s -o $@ $<

$(N64_ROOTFS_DEVNODES): $(N64_DEVNODES_SRCS) Makefile
	awk -v cons_major="$(N64_CONS_MAJOR)" -v cons_minor="$(N64_CONS_MINOR)" -v pty_enabled="$(N64_PTY_ENABLED)" -v pty_nunits="$(N64_PTY_NUNITS)" -f $(N64_DEVNODES_AWK) $(TOPSRC)/sys/n64/romdisk.h $(TOPSRC)/sys/n64/ramswap.h $(TOPSRC)/sys/n64/devmajors.h $(TOPSRC)/sys/include/conf.h $(TOPSRC)/sys/include/pty.h > $@

$(N64_ROOTFS_BUILD_MANIFEST): $(N64_ROOTFS_MANIFEST) $(N64_ROOTFS_DEVNODES)
	cp $(N64_ROOTFS_MANIFEST) $@
	cat $(N64_ROOTFS_DEVNODES) >> $@

$(N64_ROOTFS_BASE_STAMP): $(N64_ROOTFS_FILES) $(N64_ROOTFS_DIRS) $(N64_TERMCAP)
	rm -rf $(N64_ROOTFS_STAGE)
	mkdir -p $(N64_ROOTFS_STAGE)
	cp -R $(N64_ROOTFS_DIR)/. $(N64_ROOTFS_STAGE)/
	cp $(N64_TERMCAP) $(N64_ROOTFS_STAGE)/etc/termcap
	mkdir -p $(N64_ROOTFS_STAGE)/sbin
	mkdir -p $(N64_ROOTFS_STAGE)/bin
	mkdir -p $(N64_ROOTFS_STAGE)/libexec
	mkdir -p $(N64_ROOTFS_STAGE)/share/misc
	mkdir -p $(N64_ROOTFS_STAGE)/share/man/cat1
	mkdir -p $(N64_ROOTFS_STAGE)/share/man/cat8
	touch $@

$(N64_ROOTFS_USER_STAMP): $(N64_ROOTFS_BASE_STAMP) $(N64_USERLAND_STAMP) $(N64_MAKEWHATIS_SED)
	$(N64_SRC_MAKE) install
	rm -f $(N64_ROOTFS_WHATIS).tmp
	touch $(N64_ROOTFS_WHATIS).tmp
	for file in `find $(N64_ROOTFS_STAGE)/share/man/cat* -type f -name '*.0' -print`; do \
	    sed -n -f $(N64_MAKEWHATIS_SED) $$file >> $(N64_ROOTFS_WHATIS).tmp; \
	done
	sort -u $(N64_ROOTFS_WHATIS).tmp > $(N64_ROOTFS_WHATIS)
	rm -f $(N64_ROOTFS_WHATIS).tmp
	touch $@

rootfs.img: $(FSUTIL) $(N64_ROOTFS_BUILD_MANIFEST) $(N64_ROOTFS_USER_STAMP)
	rm -f $@
	$(FSUTIL) --new --endian=big --size=$(N64_ROOTFS_KBYTES) --manifest=$(N64_ROOTFS_BUILD_MANIFEST) $@ $(N64_ROOTFS_STAGE)
	$(FSUTIL) --check $@

$(TOPSRC)/src/crt0.o: $(N64_CRT0_SRCS)
	$(N64_SRC_MAKE) startup-mips

$(TOPSRC)/src/libc.a: $(TOPSRC)/src/crt0.o $(N64_LIBC_SRCS)
	$(N64_SRC_MAKE) libc

$(N64_USERLAND_STAMP): $(N64_USER_LDSCRIPT) $(N64_CRT0_SRCS) $(N64_LIBC_SRCS) $(N64_LIBUTIL_SRCS) $(N64_USER_SRCS)
	$(N64_SRC_MAKE) -B all
	touch $@

$(FSUTIL):
	$(MAKE) -C $(TOPSRC)/tools/fsutil

$(ELF2AOUT): $(ELF2AOUT_SRCS)
	$(MAKE) -C $(TOPSRC)/tools/elf2aout

preflight.z64: stage0.stripped.elf rootfs.img
	$(N64_TOOL) --toc --title "RETROBSD N64" --output $@ --align 256 stage0.stripped.elf --align 1024 rootfs.img

kernel.z64: kernel_stage0.stripped.elf rootfs.img
	$(N64_TOOL) --toc --title "RETROBSD N64" --output $@ --align 256 kernel_stage0.stripped.elf --align 1024 rootfs.img

preflight.o: ../preflight.c ${SYSTEM_DEP}
	${COMPILE_C}

startup.o: ../startup.S ${SYSTEM_DEP}
	${COMPILE_S}

ioconf.o: ioconf.c ${SYSTEM_DEP}
	${COMPILE_C}

${SYSTEM_OBJ} swapunix.o preflight.o: | machine sys .deps

clean:
	$(N64_SRC_MAKE) clean
	rm -rf *.o *.elf *.bin *.img *.dis *.nm *.z64 *.d a.out n64-init \
	    .deps machine sys $(N64_ROOTFS_STAGE) $(N64_ROOTFS_DEVNODES) \
	    $(N64_ROOTFS_BUILD_MANIFEST) $(N64_KERNEL_LDSCRIPT) \
	    $(N64_USER_LDSCRIPT) $(N64_USERLAND_STAMP)

clean-all: clean
	rm -f Makefile ioconf.c swap*.c vers.c

reconfig ioconf.c swapunix.c: Config ../../../tools/kconfig/kconfig | machine sys
	../../../tools/kconfig/kconfig Config
	$(MAKE) clean

machine:
	ln -s .. $@

sys:
	ln -s ../../include $@

.deps:
	mkdir .deps

%RULES

-include .deps/*.dep
