#
# Full N64 hardware image: GCC kernel and GCC userland.
#
KERNEL_COMPILER := gcc
USERLAND_COMPILER := gcc

N64_USERLAND_CPU := vr4300
N64_USERLAND_FLOAT := hard
N64_USERLAND_ENDIAN := big
N64_USERLAND_EXEC_FORMAT := elf

N64_MINIMAL_UART_ONLY := 0
N64_MINIMAL_ROOTFS := 0
N64_ROOTFS_KBYTES := 24576
N64_ROOTFS_NATIVE_PCC := 1
