#
# Full N64 hardware image: GCC kernel and PCC userland.
#
KERNEL_COMPILER := gcc
USERLAND_COMPILER := pcc

N64_USERLAND_CPU := vr4300
N64_USERLAND_FLOAT := hard
N64_USERLAND_ENDIAN := big
N64_USERLAND_EXEC_FORMAT := elf

N64_MINIMAL_UART_ONLY := 0
N64_MINIMAL_ROOTFS := 0
N64_ROOTFS_KBYTES := 32768
N64_ROOTFS_NATIVE_PCC := 1
MIPS_ROOTFS_NATIVE_PCC := 1
