#
# Minimal N64 hardware-test image: PCC kernel and PCC userland, both using
# the native ReBSD MIPS assembler and linker.
#
N64_KERNEL_COMPILER := pcc
N64_USERLAND_COMPILER := pcc
N64_USERLAND_CPU := vr4300
N64_USERLAND_FLOAT := hard
N64_USERLAND_ENDIAN := big
N64_USERLAND_EXEC_FORMAT := aout

N64_MINIMAL_UART_ONLY := 1
N64_MINIMAL_ROOTFS := 1
N64_MINIMAL_PCC_SMOKE := 1
N64_ROOTFS_NATIVE_PCC := 1
MIPS_ROOTFS_NATIVE_PCC := 1

N64_USB_GDB := 0
N64_RESET_DUMP := 1

N64_STAGE0_RESERVED_BYTES := 0x00080000
