#!/bin/sh
# Common System V runlevel dispatcher.  Machine initialization belongs in
# /etc/rc.sysinit; this file contains no architecture-specific policy.

HOME=/; export HOME
PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

case "$1" in
0|1|2|3|4|5|6|S|s)
        level=$1
        ;;
*)
        echo "usage: /etc/rc runlevel" >/dev/console
        exit 2
        ;;
esac

status=0
for class in K S; do
        case "$class" in
        K) operation=stop ;;
        S) operation=start ;;
        esac
        for script in /etc/rc${level}.d/${class}[0-9][0-9]*; do
                if test ! -f "$script"; then
                        continue
                fi
                /bin/sh "$script" "$operation"
                rc=$?
                if test $rc -ne 0; then
                        echo "$script: $operation failed ($rc)" >/dev/console
                        status=$rc
                fi
        done
done
exit $status
