.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)ranlib.1	6.7 (Berkeley) 5/9/91
.\"
.TH RANLIB 1 "July 4, 2026" "ReBSD"
.AT 3
.UC 6
.SH NAME
ranlib \- create an index for ReBSD archive libraries
.SH SYNOPSIS
.B ranlib
[
.B \-tv
]
.I file
\&...
.SH DESCRIPTION
.B ranlib
creates the
.B __.SYMDEF
symbol table used by
.BR ld (1)
when searching ReBSD
.B a.out
archive libraries.
The table is prepended to the archive.
Archive members that are not ReBSD object files, and symbols not useful to
the linker, are ignored.
.PP
The options are as follows:
.TP
.B \-t
Update the modification time of an existing
.B __.SYMDEF
member.
This time is compared by the loader with the modification time of the
archive to verify that the table is up-to-date with respect to the
archive.
If the modification time has been changed without any change to the
archive (for example, by a
.IR cp (1) ) ,
the
.B \-t
option can be used to ``touch'' the modification time so that it
appears that the table is up-to-date.
.TP
.B \-v
Print the generated symbol map.
.SH FILES
.TP 14
/tmp
default temporary file directory
.TP 14
ranlib.XXXXXX
temporary file names
.SH SEE ALSO
.IR ar (1) ,
.IR ld (1) ,
.IR lorder (1) ,
.IR nm (1) ,
.IR ranlib (5)
.SH HISTORY
A
.B ranlib
command appeared in Version 7 AT&T UNIX.
