#!/usr/bin/env python3
"""Generate the kernel version and read-only build metadata."""

import argparse
import json
import re


def c_string(value):
    return json.dumps(value, ensure_ascii=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--version-header", required=True)
    parser.add_argument("--ident", required=True)
    parser.add_argument("--build-number", required=True, type=int)
    parser.add_argument("--build-date", required=True)
    parser.add_argument("--compiler", required=True)
    parser.add_argument("--build-user", required=True)
    parser.add_argument("--build-host", required=True)
    parser.add_argument("--toolchain", required=True)
    parser.add_argument("--toolchain-version", required=True)
    parser.add_argument("--git-rev", required=True)
    parser.add_argument("--git-branch", required=True)
    parser.add_argument("--dirty", required=True, type=int, choices=(0, 1))
    parser.add_argument("--target", required=True)
    parser.add_argument("--cpu", required=True)
    parser.add_argument("--fpu", required=True)
    parser.add_argument("--byteorder", required=True,
                        choices=("big", "little"))
    args = parser.parse_args()

    with open(args.version_header, "r", encoding="ascii") as header:
        header_text = header.read()
    release_match = re.search(
        r'^#define\s+REBSD_RELEASE\s+"([^"]+)"',
        header_text, re.MULTILINE)
    codename_match = re.search(
        r'^#define\s+REBSD_CODENAME\s+"([^"]+)"',
        header_text, re.MULTILINE)
    if release_match is None or codename_match is None:
        parser.error("REBSD_RELEASE or REBSD_CODENAME is missing from " +
                     args.version_header)
    release = release_match.group(1)
    codename = codename_match.group(1)

    osrelease = "%s-%s" % (release, codename)
    kernel_version = "ReBSD %s (%s) #%d: %s" % (
        osrelease, args.ident, args.build_number, args.build_date)
    buildinfo = "\n".join((
        "version: ReBSD %s" % osrelease,
        "codename: %s" % codename,
        "build: #%d" % args.build_number,
        "build date: %s" % args.build_date,
        "compiler: %s" % args.compiler,
        "toolchain: %s" % args.toolchain,
        "toolchain version: %s" % args.toolchain_version,
        "git revision: %s" % args.git_rev,
        "git branch: %s" % args.git_branch,
        "git dirty: %s" % ("yes" if args.dirty else "no"),
        "target: %s" % args.target,
        "cpu: %s" % args.cpu,
        "fpu: %s" % args.fpu,
        "byteorder: %s" % args.byteorder,
    ))

    strings = (
        ("version", kernel_version),
        ("rebsd_compiler", args.compiler),
        ("rebsd_builduser", args.build_user),
        ("rebsd_buildhost", args.build_host),
        ("rebsd_toolchain", args.toolchain),
        ("rebsd_toolchain_version", args.toolchain_version),
        ("rebsd_gitrev", args.git_rev),
        ("rebsd_branch", args.git_branch),
        ("rebsd_buildinfo", buildinfo),
        ("rebsd_cpu", args.cpu),
        ("rebsd_fpu", args.fpu),
    )
    with open(args.output, "w", encoding="ascii") as output:
        output.write("/* Generated by sys/mips/tools/gen-vers.py. */\n")
        for name, value in strings:
            output.write("const char %s[] = %s;\n" %
                         (name, c_string(value)))
        output.write("const int rebsd_build = %d;\n" % args.build_number)
        output.write("const int rebsd_dirty = %d;\n" % args.dirty)


if __name__ == "__main__":
    main()
