#!/usr/bin/env python3
import argparse
import os
import shutil
import struct
import subprocess
import sys
from pathlib import Path


VERSION = "1.2.0.DEVEL"
TARGSTR = "mips-unknown-rebsd"
VERSSTR = f"Portable C Compiler {VERSION} 20231021 for {TARGSTR}"


def q(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def run(cmd, *, cwd=None, env=None):
    print("$ " + " ".join(str(c) for c in cmd))
    subprocess.run([str(c) for c in cmd], cwd=cwd, env=env, check=True)


def write_config(path, *, host_big_endian, pointer_size, have_strl):
    lines = [
        "/* Generated by sys/mips/tools/native-pcc-build.py. */",
        "#define AOUTABI 1",
        "#define HAVE_ALLOCA 1",
        "#define HAVE_ALLOCA_H 1",
        "#define HAVE_C99_FORMAT 1",
        "#define HAVE_FFS 1",
        "#define HAVE_GETOPT 1",
        "#define HAVE_INTTYPES_H 1",
        "#define HAVE_LIBM 1",
        "#define HAVE_MATH_H 1",
        "#define HAVE_MKSTEMP 1",
        "#define HAVE_SNPRINTF 1",
        "#define HAVE_STDINT_H 1",
        "#define HAVE_STDIO_H 1",
        "#define HAVE_STDLIB_H 1",
        "#define HAVE_STRINGS_H 1",
        "#define HAVE_STRING_H 1",
        "#define HAVE_STRTOLD 1",
        "#define HAVE_SYS_STAT_H 1",
        "#define HAVE_SYS_TYPES_H 1",
        "#define HAVE_SYS_WAIT_H 1",
        "#define HAVE_UNISTD_H 1",
        "#define HAVE_VFORK 1",
        "#define HAVE_VSNPRINTF 1",
        f"#define PACKAGE_NAME {q('Portable C Compiler')}",
        f"#define PACKAGE_STRING {q('Portable C Compiler ' + VERSION)}",
        '#define PACKAGE_TARNAME "pcc"',
        '#define PACKAGE_URL "http://pcc.ludd.ltu.se/"',
        '#define PACKAGE_BUGREPORT "pcc@lists.ludd.ltu.se"',
        f"#define PACKAGE_VERSION {q(VERSION)}",
        "#define PCC_MAJOR 1",
        "#define PCC_MINOR 2",
        "#define PCC_MINORMINOR 0",
        f"#define SIZEOF_INT_P {pointer_size}",
        "#define STDC_HEADERS 1",
        "#define TARGET_BIG_ENDIAN 1",
        f"#define TARGSTR {q(TARGSTR)}",
        f"#define VERSSTR {q(VERSSTR)}",
        "#define WCHAR_SIZE 2",
        "#define WCHAR_TYPE USHORT",
        "#define YYTEXT_POINTER 1",
    ]
    if have_strl:
        lines += ["#define HAVE_STRLCAT 1", "#define HAVE_STRLCPY 1"]
    if host_big_endian:
        lines += ["#define HOST_BIG_ENDIAN 1", "#define WORDS_BIGENDIAN 1"]
    else:
        lines += ["#define HOST_LITTLE_ENDIAN 1"]
    path.mkdir(parents=True, exist_ok=True)
    (path / "config.h").write_text("\n".join(lines) + "\n")


class Builder:
    def __init__(self, args):
        self.top = Path(args.top).resolve()
        self.src = self.top / "src/dev/pcc/pcc"
        self.builddir = Path(args.build).resolve()
        self.out = Path(args.out).resolve()
        self.rootfs = Path(args.rootfs).resolve() if args.rootfs else None
        self.gcc_wrapper = Path(args.gcc_wrapper).resolve()
        self.gcc_prefix = args.gcc_prefix
        self.rebsd_as = Path(args.as_).resolve()
        self.rebsd_ld = Path(args.ld).resolve()
        self.crt0 = Path(args.crt0).resolve()
        self.libdir = Path(args.libdir).resolve()
        self.host_cc = args.host_cc
        self.bison = args.bison
        self.flex = args.flex
        self.with_cxx = args.with_cxx
        self.env = os.environ.copy()
        self.env["N64_AOUT_TOPSRC"] = str(self.top)
        self.env["N64_AOUT_AS"] = str(self.rebsd_as)
        self.env["N64_PREFIX"] = self.gcc_prefix
        self.host_config = self.builddir / "host-config"
        self.target_config = self.builddir / "target-config"
        self.objects = self.builddir / "obj"

    def check(self):
        for path in [self.src, self.gcc_wrapper, self.rebsd_as,
                     self.rebsd_ld, self.crt0, self.libdir]:
            if not path.exists():
                raise FileNotFoundError(path)

    def prepare(self):
        if self.builddir.exists():
            shutil.rmtree(self.builddir)
        if self.out.exists():
            shutil.rmtree(self.out)
        self.objects.mkdir(parents=True)
        self.out.mkdir(parents=True)
        write_config(
            self.host_config,
            host_big_endian=(sys.byteorder == "big"),
            pointer_size=struct.calcsize("P"),
            have_strl=True,
        )
        write_config(self.target_config, host_big_endian=True, pointer_size=4,
                     have_strl=False)

    def host_flags(self, component_dir):
        return [
            "-O2",
            "-DGCC_COMPAT",
            "-DPCC_DEBUG",
            "-DPCC_DEBUGFP_NATIVE_STRTOLD",
            "-D_ISOC99_SOURCE",
            "-Dos_rebsd",
            "-Dmach_mips",
            "-DTARGOSVER=0",
            "-DTARGET_BIG_ENDIAN=1",
            "-I", self.host_config,
            "-I", component_dir,
            "-I", self.src / "mip",
            "-I", self.src / "arch/mips",
            "-I", self.src / "os/rebsd",
            "-I", self.src / "common",
        ]

    def target_flags(self, component_build, component_src, *, lang_cxx=False,
                     cpp=False, driver=False):
        flags = [
            "-Os",
            "-fno-builtin",
            "-fno-stack-protector",
            "-fcommon",
            "-DGCC_COMPAT",
            "-DPCC_DEBUG",
            "-D_ISOC99_SOURCE",
            "-Dos_rebsd",
            "-Dmach_mips",
            "-DTARGOSVER=0",
            "-DTARGET_BIG_ENDIAN=1",
            "-I", self.target_config,
            "-I", component_build,
            "-I", component_src,
            "-I", self.src / "mip",
            "-I", self.src / "arch/mips",
            "-I", self.src / "os/rebsd",
            "-I", self.src / "common",
        ]
        if lang_cxx:
            flags.append("-DLANG_CXX")
        if cpp:
            flags += ["-DNVMPGS=4"]
        if driver:
            flags += [
                f"-DLIBEXECDIR={q('/usr/libexec/pcc/')}",
                f"-DINCLUDEDIR={q('/usr/include/')}",
                f"-DPCCINCDIR={q('/usr/lib/pcc/' + TARGSTR + '/' + VERSION + '/include/')}",
                f"-DPCCLIBDIR={q('/usr/lib/pcc/' + TARGSTR + '/' + VERSION + '/lib/')}",
                f"-DCXXPROGNAME={q('p++')}",
                f"-DCPPROGNAME={q('cpp')}",
                f"-DCC0={q('cc0')}",
                f"-DCC1={q('cc1')}",
            ]
        return [str(f) for f in flags]

    def generate_ccom_files(self, component):
        component_src = self.src / f"cc/{component}"
        component_build = self.builddir / component
        component_build.mkdir(parents=True)

        run([
            self.host_cc,
            *self.host_flags(component_src),
            "-DMKEXT",
            "-o",
            component_build / "mkext",
            self.src / "mip/mkext.c",
            self.src / "mip/common.c",
            self.src / "arch/mips/table.c",
        ])
        run([component_build / "mkext"], cwd=component_build)

        run([self.bison, "-y", "-d", component_src / "cgram.y"],
            cwd=component_build)
        (component_build / "y.tab.c").replace(component_build / "cgram.c")
        (component_build / "y.tab.h").replace(component_build / "cgram.h")
        run([self.flex, "-o", component_build / "scan.c",
             component_src / "scan.l"])
        return component_src, component_build

    def obj_path(self, component, name):
        path = self.objects / component / f"{name}.o"
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    def compile_target(self, component, name, source, flags):
        obj = self.obj_path(component, name)
        run([self.gcc_wrapper, *flags, "-c", "-o", obj, source],
            env=self.env)
        return obj

    def link_target(self, output, objects, *, need_math=True):
        cmd = [
            self.rebsd_ld,
            "-X",
            "-d",
            "-e",
            "_start",
            "-o",
            output,
            self.crt0,
            *objects,
            "-L",
            self.libdir,
        ]
        if need_math:
            cmd.append("-lm")
        cmd += ["-lc", "-lpcc"]
        run(cmd)

    def build_cpp(self):
        component = "cpp"
        srcdir = self.src / "cc/cpp"
        builddir = self.builddir / component
        builddir.mkdir(parents=True)
        flags = self.target_flags(builddir, srcdir, cpp=True)
        specs = [
            ("compat", self.src / "common/compat.c"),
            ("cpp", srcdir / "cpp.c"),
            ("cpc", srcdir / "cpc.c"),
            ("token", srcdir / "token.c"),
        ]
        objects = [
            self.compile_target(component, name, source, flags)
            for name, source in specs
        ]
        self.link_target(self.out / "cpp", objects, need_math=True)

    def build_driver(self):
        component = "cc"
        srcdir = self.src / "cc/cc"
        builddir = self.builddir / component
        builddir.mkdir(parents=True)
        flags = self.target_flags(builddir, srcdir, driver=True)
        flags += ["-I", str(self.src / "cc/driver")]
        specs = [
            ("cc", srcdir / "cc.c"),
            ("compat", self.src / "common/compat.c"),
            ("strlist", self.src / "cc/driver/strlist.c"),
            ("xalloc", self.src / "cc/driver/xalloc.c"),
        ]
        objects = [
            self.compile_target(component, name, source, flags)
            for name, source in specs
        ]
        self.link_target(self.out / "cc", objects, need_math=True)

    def build_ccom(self):
        component = "ccom"
        srcdir, builddir = self.generate_ccom_files(component)
        flags = self.target_flags(builddir, srcdir)
        specs = [
            ("builtins", srcdir / "builtins.c"),
            ("cgram", builddir / "cgram.c"),
            ("code", self.src / "arch/mips/code.c"),
            ("common", self.src / "mip/common.c"),
            ("compat", self.src / "common/compat.c"),
            ("complex", srcdir / "complex.c"),
            ("dwarf", srcdir / "dwarf.c"),
            ("external", builddir / "external.c"),
            ("gcc_compat", srcdir / "gcc_compat.c"),
            ("init", srcdir / "init.c"),
            ("inline", srcdir / "inline.c"),
            ("local", self.src / "arch/mips/local.c"),
            ("local2", self.src / "arch/mips/local2.c"),
            ("main", srcdir / "main.c"),
            ("match", self.src / "mip/match.c"),
            ("optim", srcdir / "optim.c"),
            ("optim2", self.src / "mip/optim2.c"),
            ("order", self.src / "arch/mips/order.c"),
            ("params", srcdir / "params.c"),
            ("pftn", srcdir / "pftn.c"),
            ("reader", self.src / "mip/reader.c"),
            ("regs", self.src / "mip/regs.c"),
            ("scan", builddir / "scan.c"),
            ("softfloat", self.src / "common/softfloat.c"),
            ("stabs", srcdir / "stabs.c"),
            ("symtabs", srcdir / "symtabs.c"),
            ("table", self.src / "arch/mips/table.c"),
            ("trees", srcdir / "trees.c"),
            ("unicode", self.src / "common/unicode.c"),
        ]
        objects = [
            self.compile_target(component, name, source, flags)
            for name, source in specs
        ]
        self.link_target(self.out / "ccom", objects, need_math=True)

    def build_cxxcom(self):
        component = "cxxcom"
        srcdir, builddir = self.generate_ccom_files(component)
        flags = self.target_flags(builddir, srcdir, lang_cxx=True)
        specs = [
            ("builtins", srcdir / "builtins.c"),
            ("cgram", builddir / "cgram.c"),
            ("code", self.src / "arch/mips/code.c"),
            ("common", self.src / "mip/common.c"),
            ("compat", self.src / "common/compat.c"),
            ("external", builddir / "external.c"),
            ("gcc_compat", srcdir / "gcc_compat.c"),
            ("init", srcdir / "init.c"),
            ("inline", srcdir / "inline.c"),
            ("local", self.src / "arch/mips/local.c"),
            ("local2", self.src / "arch/mips/local2.c"),
            ("main", srcdir / "main.c"),
            ("cxxcode", srcdir / "cxxcode.c"),
            ("match", self.src / "mip/match.c"),
            ("optim", srcdir / "optim.c"),
            ("optim2", self.src / "mip/optim2.c"),
            ("order", self.src / "arch/mips/order.c"),
            ("pftn", srcdir / "pftn.c"),
            ("reader", self.src / "mip/reader.c"),
            ("regs", self.src / "mip/regs.c"),
            ("scan", builddir / "scan.c"),
            ("stabs", srcdir / "stabs.c"),
            ("symtabs", srcdir / "symtabs.c"),
            ("table", self.src / "arch/mips/table.c"),
            ("trees", srcdir / "trees.c"),
        ]
        objects = [
            self.compile_target(component, name, source, flags)
            for name, source in specs
        ]
        self.link_target(self.out / "cxxcom", objects, need_math=True)

    def build(self):
        self.check()
        self.prepare()
        self.build_cpp()
        self.build_ccom()
        if self.with_cxx:
            self.build_cxxcom()
        self.build_driver()
        outputs = ["cc", "cpp", "ccom"]
        if self.with_cxx:
            outputs.append("cxxcom")
        for name in outputs:
            path = self.out / name
            if not path.is_file() or path.stat().st_size == 0:
                raise RuntimeError(f"missing {path}")
            os.chmod(path, 0o775)
        print(f"native PCC staged in {self.out}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--top", required=True)
    parser.add_argument("--build", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--rootfs")
    parser.add_argument("--gcc-wrapper", required=True)
    parser.add_argument("--gcc-prefix", required=True)
    parser.add_argument("--as", dest="as_", required=True)
    parser.add_argument("--ld", required=True)
    parser.add_argument("--crt0", required=True)
    parser.add_argument("--libdir", required=True)
    parser.add_argument("--host-cc", default=os.environ.get("HOSTCC", "cc"))
    parser.add_argument("--bison", default=os.environ.get("BISON", "bison"))
    parser.add_argument("--flex", default=os.environ.get("FLEX", "flex"))
    parser.add_argument("--with-cxx", action="store_true",
                        help="also build the unsupported cxxcom diagnostic binary")
    args = parser.parse_args()
    Builder(args).build()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
