#
# Makefile template for RetroBSD on Nintendo 64.
#
include ../../../target-n64.mk

TOPSRC          = ../../..
S               = ../..

N64_KERNEL_ARCH = -EB -march=vr4300 -mtune=vr4300 -mips3 -mabi=32
N64_KERNEL_BASE = -G0 -mno-abicalls -fno-pic -ffreestanding -fno-builtin \
                  -fomit-frame-pointer
N64_KERNEL_CODE = $(N64_KERNEL_BASE) -msoft-float
N64_FPU_CODE    = $(N64_KERNEL_BASE) -mhard-float
N64_TRACE       ?= 0
N64_DEBUG_UART_ONLY ?= 0
N64_BUILD_MODE_STAMP = .build-mode.$(N64_DEBUG_UART_ONLY)
ifeq ($(N64_DEBUG_UART_ONLY),1)
PARAM := $(filter-out -DVIDEO_ENABLED -DINPUT_ENABLED \
    -DUSBNET_ENABLED -DUSBNET_ECM -DUSBNET_VENDOR,$(PARAM))
PARAM += -DN64_DEBUG_UART_ONLY -DN64_DEBUG_USERMEM_4M -DN64_PCC_FPE_TRACE
endif
N64_ROOTFS_KBYTES ?= 16384
N64_ROOTFS_COMMON_DIR ?= $(TOPSRC)/sys/mips/rootfs
N64_ROOTFS_BOARD_DIR ?= $(TOPSRC)/sys/mips/n64/rootfs
N64_ROOTFS_MANIFEST ?= $(TOPSRC)/sys/mips/rootfs.manifest
N64_ROOTFS_DEVNODES = rootfs.devnodes.manifest
N64_ROOTFS_BUILD_MANIFEST = rootfs.generated.manifest
N64_ROOTFS_STAGE = rootfs.stage
N64_ROOTFS_USR_BIN = $(N64_ROOTFS_STAGE)/usr/bin
N64_ROOTFS_USR_LIB = $(N64_ROOTFS_STAGE)/usr/lib
N64_ROOTFS_USR_LIBEXEC = $(N64_ROOTFS_STAGE)/usr/libexec
N64_ROOTFS_USR_INCLUDE = $(N64_ROOTFS_STAGE)/usr/include
N64_ROOTFS_USR_SHARE = $(N64_ROOTFS_STAGE)/usr/share
N64_ROOTFS_BASE_STAMP = $(N64_ROOTFS_STAGE)/.base
N64_ROOTFS_USER_STAMP = $(N64_ROOTFS_STAGE)/.userland.$(N64_USERLAND_COMPILER)
N64_ROOTFS_USER_COMPAT_STAMP = $(N64_ROOTFS_STAGE)/.userland
N64_ROOTFS_WHATIS = $(N64_ROOTFS_USR_SHARE)/man/whatis
N64_USR_BIN_FILES = aout apropos ar as awk basename basic cal calendar cb chgrp \
                    cmp col comm compress deco diff diskspeed du ed egrep \
                    emg env fbset fbview fgrep file find fold forth grep \
                    groups head hostid id join last ld man matrix-as-vr4300 \
                    matrix-as-vr4300.sh make md5 med mesg more \
                    n64input nice nm nohup od pagesize pdc picoc pr \
                    printf printenv ps ptytest ranlib renice renumber retroforth rev \
                    rgbled rmail romfsctl setty size sl smux \
                    smoke-as-vr4300 smoke-as-vr4300.sh sort split strip sum \
                    sysctl tail tar tcl tee telnet time touch tsort tty \
                    uncompress uniq vmstat w wc wget whatis whereis who \
                    whoami xargs zcat
N64_USR_LIBEXEC_FILES = bigram code
N64_ROOTFS_CAT1_PAGES = apropos awk basename cal cat cb chgrp chmod cmp col comm \
                        compress cp date dd df diff du echo ed expr false \
                        file find fold grep head hostid join kill last ln \
                        login ls make man mesg mkdir more mv nice od pagesize pr ps \
                        printenv pwd rev rm rmail rmdir \
                        sed sh size sleep sort split strip sum tail tar tee \
                        time touch tr true tsort tty uniq vmstat w wc whatis who
N64_ROOTFS_CMD_CAT1_SOURCES = emg:emg env:env sl:sl wget:wget
N64_ROOTFS_CAT1_ALIASES = egrep:grep fgrep:grep uncompress:compress \
                          zcat:compress nohup:nice
N64_ROOTFS_CAT8_PAGES = fsck getty sync
N64_ROOTFS_CAT8_ALIASES = fastboot:reboot halt:reboot poweroff:reboot \
                          bootloader:reboot
N64_ROOTFS_FILES = $(shell find $(N64_ROOTFS_COMMON_DIR) \
                   $(N64_ROOTFS_BOARD_DIR) -type f 2>/dev/null)
N64_ROOTFS_DIRS = $(shell find $(N64_ROOTFS_COMMON_DIR) \
                  $(N64_ROOTFS_BOARD_DIR) -type d 2>/dev/null)
N64_INCLUDE_SRCS = $(shell find $(TOPSRC)/include $(TOPSRC)/sys/include \
                   $(TOPSRC)/sys/mips/include $(TOPSRC)/sys/mips/n64/include \
                   -type f -name '*.h' \
                   2>/dev/null) \
                   $(wildcard $(TOPSRC)/sys/mips/*.h \
                   $(TOPSRC)/sys/mips/n64/*.h)
N64_INCLUDE_LINKS = $(shell find $(TOPSRC)/include -maxdepth 1 -type l \
                    2>/dev/null)
N64_NATIVE_DIR = n64-native-runtime
N64_NATIVE_TREE = $(N64_NATIVE_DIR)/tree
N64_NATIVE_TOOLS = n64-native-tools
N64_NATIVE_HOST_INCLUDE = $(N64_NATIVE_TOOLS)/include
N64_NATIVE_HOST_INCLUDE_STAMP = $(N64_NATIVE_HOST_INCLUDE)/.stamp
N64_NATIVE_AS = $(N64_NATIVE_TOOLS)/as
N64_NATIVE_LD = $(N64_NATIVE_TOOLS)/ld
N64_NATIVE_AOUT_AR = $(N64_NATIVE_TOOLS)/ar
N64_NATIVE_AOUT_RANLIB = $(N64_NATIVE_TOOLS)/ranlib
N64_NATIVE_AOUT_NM = $(N64_NATIVE_TOOLS)/nm
N64_NATIVE_AOUT_SIZE = $(N64_NATIVE_TOOLS)/size
N64_NATIVE_AOUT_STRIP = $(N64_NATIVE_TOOLS)/strip
N64_HOST_CPP = $(N64_NATIVE_TOOLS)/cpp-host
N64_HOST_CPP_BUILD = $(N64_NATIVE_TOOLS)/cpp-host-build
N64_HOST_CCOM = $(N64_NATIVE_TOOLS)/ccom-host
N64_HOST_CCOM_BUILD = $(N64_NATIVE_TOOLS)/ccom-host-build
N64_NATIVE_CRT0_SRC = $(TOPSRC)/lib/startup/crt0.s
N64_NATIVE_CC_SCRIPT = $(TOPSRC)/sys/mips/n64/native/n64-aout-cc.sh
N64_NATIVE_ASWRAP_SCRIPT = $(TOPSRC)/sys/mips/n64/native/n64-aout-as.sh
N64_HOST_PORTABLECC_SCRIPT = $(TOPSRC)/sys/mips/n64/native/smoke-host-portablecc.sh
N64_HOST_CPP_BUILD_SCRIPT = $(TOPSRC)/sys/mips/n64/native/build-host-cpp.sh
N64_HOST_CCOM_BUILD_SCRIPT = $(TOPSRC)/sys/mips/n64/native/build-host-ccom.sh
N64_HOST_PCC_SMOKE_SCRIPT = $(TOPSRC)/sys/mips/n64/native/smoke-host-pcc.sh
N64_NATIVE_AS_SMOKE_SCRIPT = $(TOPSRC)/sys/mips/n64/native/smoke-as-vr4300.sh
N64_NATIVE_AS_MATRIX_SCRIPT = $(TOPSRC)/sys/mips/n64/native/matrix-as-vr4300.sh
N64_NATIVE_AOUT_SMOKE_SCRIPT = $(TOPSRC)/sys/mips/n64/native/smoke-aout-toolchain.sh
N64_NATIVE_PCC_BUILD_SCRIPT = $(TOPSRC)/sys/mips/tools/native-pcc-build.py
N64_NATIVE_CC = sh $(abspath $(N64_NATIVE_CC_SCRIPT))
N64_NATIVE_ASWRAP = sh $(abspath $(N64_NATIVE_ASWRAP_SCRIPT))
N64_NATIVE_MKHOSTINCLUDE = $(TOPSRC)/sys/mips/n64/native/mkhostinclude.sh
N64_COMMON_MACHINE_HEADERS = cpu elf_machdep float fpu io limits
N64_NATIVE_AR = $(N64_PREFIX)ar
N64_GNU_AS ?= $(N64_PREFIX)as
N64_NATIVE_STAMP = $(N64_NATIVE_DIR)/.built
N64_NATIVE_LIBS = crt0.o libc.a libm.a libpcc.a
N64_NATIVE_PCC_BUILD = n64-native-pcc-build
N64_NATIVE_PCC_DIR = n64-native-pcc
N64_NATIVE_PCC_STAMP = $(N64_NATIVE_PCC_DIR)/.built
N64_PCC_REGRESS_SCRIPT = $(TOPSRC)/sys/mips/tools/pcc-regress.py
N64_PCC_TEST_SRCS = $(shell find $(TOPSRC)/src/dev/pcc/pcc-tests/regress \
                   -type f 2>/dev/null)
N64_PCC_HW_REGRESS_MANIFEST = rootfs.pcc-hw-regress.manifest
N64_PCC_DEBUG_ROOTFS_SCRIPT = $(TOPSRC)/sys/mips/tools/n64-pcc-debug-rootfs.py
N64_PCC_DEBUG_ROOTFS_STAGE = rootfs.pcc-debug.stage
N64_PCC_DEBUG_ROOTFS_IMG = rootfs.pcc-debug.img
N64_PCC_DEBUG_TOC_ROOTFS_IMG = rootfs.img
N64_PCC_DEBUG_ROOTFS_MANIFEST = rootfs.pcc-debug.manifest
N64_PCC_DEBUG_ROOTFS_KBYTES ?= 6144
N64_PCC_DEBUG_RUNNER_SRC = $(TOPSRC)/sys/mips/tools/n64-pcc-debug-runner.c
N64_PCC_DEBUG_RUNNER_OBJ = n64-pcc-debug-runner.o
N64_PCC_DEBUG_RUNNER = n64-pcc-debug-runner
N64_LINPACK_SMOKE_SCRIPT = $(TOPSRC)/sys/mips/tools/linpack-smoke.py
N64_LINPACK_SMOKE_SRC = $(TOPSRC)/sys/mips/rootfs/root/linpack.c
N64_LINPACK_SMOKE_OUT ?= /private/tmp/rebsd-n64-linpack-smoke
N64_LINPACK_SMOKE_MANIFEST = rootfs.linpack-smoke.manifest
N64_LINPACK_ROOTFS_STAMP = $(N64_ROOTFS_STAGE)/.linpack-smoke
N64_ROOTFS_EXTRA_STAMPS =
ifeq ($(N64_USERLAND_COMPILER),pcc)
N64_ROOTFS_EXTRA_STAMPS += $(N64_LINPACK_ROOTFS_STAMP)
endif
N64_PCC_HOST_BUILD ?= /private/tmp/rebsd-n64-pcc-build
N64_PCC_HOST_PREFIX ?= /private/tmp/rebsd-n64-pcc-install
N64_HOST_PCC = $(N64_PCC_HOST_PREFIX)/bin/mips-rebsd-pcc
N64_TERMCAP = $(TOPSRC)/src/libtermlib/termcap/termcap.small
N64_MAKEWHATIS_SED = $(TOPSRC)/src/man/makewhatis.sed
N64_DEVNODES_AWK = $(TOPSRC)/sys/mips/n64/devnodes.awk
N64_DEVNODES_SRCS = $(N64_DEVNODES_AWK) $(TOPSRC)/sys/mips/n64/romdisk.h \
                    $(TOPSRC)/sys/mips/n64/ramswap.h \
                    $(TOPSRC)/sys/mips/n64/n64cart_flash.h \
                    $(TOPSRC)/sys/mips/n64/devmajors.h \
                    $(TOPSRC)/sys/include/conf.h \
                    $(TOPSRC)/sys/include/pty.h
N64_CONS_MAJOR = $(patsubst -DCONS_MAJOR=%,%,$(filter -DCONS_MAJOR=%,$(PARAM)))
N64_CONS_MINOR = $(patsubst -DCONS_MINOR=%,%,$(filter -DCONS_MINOR=%,$(PARAM)))
N64_PTY_ENABLED = $(filter -DPTY_ENABLED,$(PARAM))
N64_PTY_NUNITS = $(patsubst -DPTY_NUNITS=%,%,$(filter -DPTY_NUNITS=%,$(PARAM)))
N64_CRT0_SRCS = $(N64_NATIVE_CRT0_SRC)
N64_LIBC_SRCS = $(shell find $(TOPSRC)/src/libc -type f \( -name '*.[chS]' -o -name '*.inc' -o -name Makefile \) 2>/dev/null)
N64_LIBM_SRCS = $(shell find $(TOPSRC)/src/libm -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_LIBPCC_DIR = $(TOPSRC)/src/dev/pcc/pcc-libs/libpcc
N64_LIBPCC_OBJS = cmpdi2.o divdi3.o fixdfdi.o fixsfdi.o fixunsdfdi.o \
                  fixunssfdi.o floatdidf.o floatdisf.o floatunsdidf.o \
                  isinf_sign.o moddi3.o muldi3.o negdi2.o qdivrem.o \
                  ucmpdi2.o udivdi3.o umoddi3.o cxmuldiv.o \
                  ashldi3.o ashrdi3.o lshrdi3.o \
                  _alloca.o unwind.o ssp.o signbit.o
N64_LIBPCC_SRCS = $(addprefix $(N64_LIBPCC_DIR)/,$(N64_LIBPCC_OBJS:.o=.c)) \
                  $(N64_LIBPCC_DIR)/quad.h \
                  $(shell find $(N64_LIBPCC_DIR)/include -type f 2>/dev/null)
N64_LIBUTIL_SRCS = $(shell find $(TOPSRC)/src/libutil -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_LIBTERMLIB_SRCS = $(shell find $(TOPSRC)/src/libtermlib -type f \( -name '*.[chS]' -o -name Makefile -o -name 'termcap.*' \) 2>/dev/null)
N64_LIBCURSES_SRCS = $(shell find $(TOPSRC)/src/libcurses -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_LIBVMF_SRCS = $(shell find $(TOPSRC)/src/libvmf -type f \( -name '*.[chS]' -o -name Makefile -o -name '*.3' \) 2>/dev/null)
N64_LIBREADLINE_SRCS = $(shell find $(TOPSRC)/src/libreadline -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_LIBTCL_SRCS = $(shell find $(TOPSRC)/src/libtcl -type f \( -name '*.[chS]' -o -name Makefile \) 2>/dev/null)
N64_CPP_SRCS = $(shell find $(TOPSRC)/src/cmd/cpp -type f \( -name '*.[chly]' -o -name Makefile \) 2>/dev/null)
N64_CCOM_SRCS = $(shell find $(TOPSRC)/src/cmd/ccom -type f \( -name '*.[chly]' -o -name Makefile \) 2>/dev/null)
N64_DEV_PCC_SRCS = $(N64_NATIVE_PCC_BUILD_SCRIPT) \
                   $(shell find $(TOPSRC)/src/dev/pcc/pcc -type f \
                   \( -name '*.[chly]' -o -name '*.h' -o -name Makefile.in \) \
                   2>/dev/null)
N64_NATIVE_TARGET_FLAGS = -DTARGET_BIG_ENDIAN -DTARGET_VR4300 \
                          -DTARGET_MIPS_STRICT_ALIGN64 \
                          -DTARGET_NO_ABICALLS
N64_NATIVE_TOOL_SRCS = $(N64_NATIVE_MKHOSTINCLUDE) $(N64_NATIVE_CC_SCRIPT) \
                       $(N64_NATIVE_ASWRAP_SCRIPT) \
                       $(N64_HOST_CPP_BUILD_SCRIPT) \
                       $(N64_HOST_CCOM_BUILD_SCRIPT) \
                       $(N64_HOST_PCC_SMOKE_SCRIPT) \
                       $(N64_NATIVE_AS_SMOKE_SCRIPT) \
                       $(N64_NATIVE_AS_MATRIX_SCRIPT) \
                       $(N64_NATIVE_AOUT_SMOKE_SCRIPT) \
                       $(TOPSRC)/src/cmd/as/as.c \
                       $(TOPSRC)/src/cmd/ld/ld.c \
                       $(TOPSRC)/src/cmd/ar/append.c \
                       $(TOPSRC)/src/cmd/ar/ar.c \
                       $(TOPSRC)/src/cmd/ar/archive.c \
                       $(TOPSRC)/src/cmd/ar/contents.c \
                       $(TOPSRC)/src/cmd/ar/delete.c \
                       $(TOPSRC)/src/cmd/ar/extract.c \
                       $(TOPSRC)/src/cmd/ar/extern.h \
                       $(TOPSRC)/src/cmd/ar/misc.c \
                       $(TOPSRC)/src/cmd/ar/move.c \
                       $(TOPSRC)/src/cmd/ar/print.c \
                       $(TOPSRC)/src/cmd/ar/replace.c \
                       $(TOPSRC)/src/cmd/ar/strmode.c \
                       $(TOPSRC)/src/cmd/ranlib/ranlib.c \
                       $(TOPSRC)/src/cmd/nm/nm.c \
                       $(TOPSRC)/src/cmd/size.c \
                       $(TOPSRC)/src/cmd/strip.c \
                       $(TOPSRC)/src/cmd/aoutio.c \
                       $(TOPSRC)/src/cmd/aoutio.h \
                       $(TOPSRC)/include/a.out.h \
                       $(TOPSRC)/include/ar.h \
                       $(TOPSRC)/include/nlist.h \
                       $(TOPSRC)/include/ranlib.h \
                       $(TOPSRC)/include/sys/exec_aout.h
N64_NATIVE_RUNTIME_SRCS = $(N64_NATIVE_TOOL_SRCS) $(N64_INCLUDE_SRCS) \
                          $(N64_NATIVE_CRT0_SRC) $(N64_LIBC_SRCS) \
                          $(N64_LIBM_SRCS) $(N64_LIBPCC_SRCS) \
                          $(TOPSRC)/target.mk $(TOPSRC)/target-n64.mk
N64_AWK_SRCS = $(shell find $(TOPSRC)/src/cmd/awk -type f \( -name '*.[chly]' -o -name Makefile -o -name tokenscript \) 2>/dev/null)
N64_BISON ?= $(if $(wildcard /opt/homebrew/opt/bison/bin/bison),/opt/homebrew/opt/bison/bin/bison,bison)
N64_YACC ?= byacc
N64_SRC_LIBS = libc libm libutil libtermlib libcurses libvmf libreadline libtcl
N64_SRC_SUBDIRS = cmd
N64_CMD_NONE = __n64_none__
N64_CMD_SUBDIRS = basic calendar chown chroot compress date2 deco dhclient diff emg env fbset \
                  fbview find fold forth fsck getty hostname id ifconfig inetd init \
                  aout ar as ld login ls make man md5 med mkfs mknod \
                  mkpasswd mount more n64input netstat nm pdc picoc ping printf pstat ptytest \
                  ranlib reboot renice retroforth rgbled romfsctl route sed setty \
                  sh shutdown sl smux stty sysctl tcl telnet \
                  telnetd test wget umount uname xargs
N64_CMD_STDS = basename cal cat cb chgrp chmod cmp col comm cp dd diskspeed \
               du echo ed fgrep file grep head hostid join kill last ln \
               mesg mkdir mv nice od pagesize pr printenv pwd rev rm rmail \
               rmdir size sleep sort split sum sync tail tar tee time touch \
               tr tsort tty uniq w wc whereis who
N64_CMD_NSTDS = egrep expr
N64_CMD_OPERATORS = df
N64_CMD_SCRIPTS = false nohup true
N64_CMD_EXTRA_SUBDIRS = deco fbset fbview n64input ptytest rgbled \
                        romfsctl tcl
N64_STB_DIR ?= /Users/sash/Work/N64/N64cart/rom/src/stb
N64_STB_SRCS = $(wildcard $(N64_STB_DIR)/stb_image.h)
N64_USER_SRCS = $(TOPSRC)/src/Makefile $(TOPSRC)/src/cmd/Makefile \
                $(shell find $(TOPSRC)/src/cmd -maxdepth 3 -type f \( -name '*.[chSy]' -o -name '*.[0-9]' -o -name '*.sh' -o -name Makefile \) 2>/dev/null) \
                $(N64_STB_SRCS)
N64_USERLAND_COMPILER ?= gcc
N64_USERLAND_STAMP = n64-userland.$(N64_USERLAND_COMPILER).stamp
N64_USERLAND_INCLUDES = -I$(abspath $(TOPSRC)/sys/mips/n64/include) \
                        -I$(abspath $(TOPSRC)/include)

ifeq ($(N64_USERLAND_COMPILER),gcc)
N64_USERLAND_CC = $(N64_PREFIX)gcc $(N64_ARCH) $(N64_CODE) $(N64_USERLAND_INCLUDES) \
                -Werror -Wno-unused-value -Wno-format-overflow \
                -Wno-attribute-alias -Wno-missing-attributes
N64_USERLAND_AS = $(N64_USERLAND_CC) -x assembler-with-cpp -c
N64_USERLAND_LD = $(N64_PREFIX)ld -m elf32ebmip
N64_USERLAND_AR = $(N64_PREFIX)ar
N64_USERLAND_RANLIB = $(N64_PREFIX)ranlib
N64_USERLAND_NM = $(N64_PREFIX)nm
N64_USERLAND_SIZE = $(N64_PREFIX)size
N64_USERLAND_OBJDUMP = $(N64_PREFIX)objdump
N64_USERLAND_ELF2AOUT = $(abspath $(TOPSRC)/tools/elf2aout/elf2aout)
N64_USERLAND_LDFLAGS = --nmagic -T$(abspath $(N64_USER_LDSCRIPT)) \
                       $(abspath $(TOPSRC)/src/crt0.o) \
                       -L$(abspath $(TOPSRC)/src)
N64_USERLAND_EXTRA_DEPS = $(N64_USERLAND_ELF2AOUT)
else ifeq ($(N64_USERLAND_COMPILER),pcc)
N64_USERLAND_CC = $(N64_HOST_PCC) $(N64_USERLAND_INCLUDES)
N64_USERLAND_AS = N64_AOUT_TOPSRC=$(abspath $(TOPSRC)) \
                  N64_AOUT_AS=$(abspath $(N64_NATIVE_AS)) \
                  N64_PREFIX=$(N64_PREFIX) \
                  sh $(abspath $(N64_NATIVE_ASWRAP_SCRIPT))
N64_USERLAND_LD = $(N64_HOST_PCC)
N64_USERLAND_AR = $(abspath $(N64_NATIVE_AOUT_AR))
N64_USERLAND_RANLIB = $(abspath $(N64_NATIVE_AOUT_RANLIB))
N64_USERLAND_NM = $(abspath $(N64_NATIVE_AOUT_NM))
N64_USERLAND_SIZE = $(abspath $(N64_NATIVE_AOUT_SIZE))
N64_USERLAND_OBJDUMP = true
N64_USERLAND_ELF2AOUT = cp
N64_USERLAND_LDFLAGS = -nostartfiles \
                       $(abspath $(N64_NATIVE_DIR)/crt0.o) \
                       -L$(abspath $(TOPSRC)/src) \
                       -L$(abspath $(N64_NATIVE_DIR))
N64_USERLAND_EXTRA_DEPS = $(N64_HOST_PCC) $(N64_NATIVE_AOUT_AR) \
                          $(N64_NATIVE_AOUT_RANLIB) $(N64_NATIVE_AOUT_NM) \
                          $(N64_NATIVE_AOUT_SIZE) $(N64_NATIVE_AS) \
                          $(N64_NATIVE_LD) \
                          $(N64_NATIVE_DIR)/libpcc.a
else
$(error Unsupported N64_USERLAND_COMPILER=$(N64_USERLAND_COMPILER))
endif

N64_SRC_MAKE = GROFF_NO_SGR=1 $(MAKE) -C $(TOPSRC)/src TARGET_PLATFORM=n64 \
               N64_USER_LDSCRIPT=$(abspath $(N64_USER_LDSCRIPT)) \
               N64_STB_DIR="$(N64_STB_DIR)" \
               DESTDIR=$(abspath $(N64_ROOTFS_STAGE)) \
               CC="$(N64_USERLAND_CC)" \
               AS="$(N64_USERLAND_AS)" \
               LD="$(N64_USERLAND_LD)" \
               AR="$(N64_USERLAND_AR)" \
               RANLIB="$(N64_USERLAND_RANLIB)" \
               NM="$(N64_USERLAND_NM)" \
               SIZE="$(N64_USERLAND_SIZE)" \
               OBJDUMP="$(N64_USERLAND_OBJDUMP)" \
               ELF2AOUT="$(N64_USERLAND_ELF2AOUT)" \
               LDFLAGS="$(N64_USERLAND_LDFLAGS)" \
               CC_STDINC=/usr/include \
               CC_LIBDIR=/usr/lib \
               CC_LIBEXECDIR=/usr/libexec \
               CC_CRT0FILE=/usr/lib/crt0.o \
               CC_CRT0FILE_PROFILE=/usr/lib/mcrt0.o \
               SRC_ONLY_LIBS="$(N64_SRC_LIBS)" \
               SRC_ONLY_SUBDIR="$(N64_SRC_SUBDIRS)" \
               CMD_ONLY_SUBDIR="$(N64_CMD_SUBDIRS)" \
               CMD_ONLY_STD="$(N64_CMD_STDS)" \
               CMD_ONLY_SCRIPT="$(N64_CMD_SCRIPTS)" \
               CMD_ONLY_NSTD="$(N64_CMD_NSTDS)" \
               CMD_ONLY_SETUID="$(N64_CMD_NONE)" \
               CMD_ONLY_OPERATOR="$(N64_CMD_OPERATORS)" \
               CMD_ONLY_KMEM="ps vmstat" \
               CMD_ONLY_TTY="$(N64_CMD_NONE)" \
               CMD_EXTRA_SUBDIR="$(N64_CMD_EXTRA_SUBDIRS)" \
               SMUX_SUBDIRS=retro \
               CMD_BUILD_STRIP=strip
N64_AWK_MAKE = $(MAKE) -C $(TOPSRC)/src/cmd/awk TARGET_PLATFORM=n64 \
               N64_USER_LDSCRIPT=$(abspath $(N64_USER_LDSCRIPT)) \
               DESTDIR=$(abspath $(N64_ROOTFS_STAGE)) \
               CC="$(N64_USERLAND_CC)" \
               AS="$(N64_USERLAND_AS)" \
               LD="$(N64_USERLAND_LD)" \
               AR="$(N64_USERLAND_AR)" \
               RANLIB="$(N64_USERLAND_RANLIB)" \
               NM="$(N64_USERLAND_NM)" \
               SIZE="$(N64_USERLAND_SIZE)" \
               OBJDUMP="$(N64_USERLAND_OBJDUMP)" \
               ELF2AOUT="$(N64_USERLAND_ELF2AOUT)" \
               LDFLAGS="$(N64_USERLAND_LDFLAGS)" \
               YACC="$(N64_YACC)"
N64_STAGE0_CONSOLE_OBJS = $(if $(filter n64cart_uart.o,$(OBJS)),stage0_n64cart_uart.o,stage0_console_null.o)
N64_STAGE0_OBJS = stage0.o stage0_loader.o $(N64_STAGE0_CONSOLE_OBJS)
N64_PREFLIGHT_CONSOLE_OBJS = $(if $(filter n64cart_uart.o,$(OBJS)),preflight_n64cart_uart.o,console_null.o)
N64_PREFLIGHT_OBJS = startup.o $(N64_PREFLIGHT_CONSOLE_OBJS) \
                     rompak.o memory.o preflight.o
N64_KERNEL_LDSCRIPT = n64.ld
N64_USER_LDSCRIPT = n64-user.ld

CC              = $(N64_PREFIX)gcc $(N64_KERNEL_ARCH) $(N64_KERNEL_CODE)
AS              = $(N64_PREFIX)gcc $(N64_KERNEL_ARCH) $(N64_KERNEL_CODE)
ASFPU           = $(N64_PREFIX)gcc $(N64_KERNEL_ARCH) $(N64_FPU_CODE)
LD              = $(N64_PREFIX)ld -m elf32ebmip
OBJDUMP         = $(N64_PREFIX)objdump
SIZE            = $(N64_PREFIX)size
STRIP           = $(N64_PREFIX)strip
NM              = $(N64_PREFIX)nm
N64_TOOL        = $(N64_TOOLCHAIN)/bin/n64tool
FSUTIL          = $(TOPSRC)/tools/fsutil/fsutil
ELF2AOUT        = $(TOPSRC)/tools/elf2aout/elf2aout
ELF2AOUT_SRCS   = $(TOPSRC)/tools/elf2aout/Makefile \
                  $(TOPSRC)/tools/elf2aout/elf2aout.c

DEPFLAGS        = -MT $@ -MP -MD -MF .deps/$*.dep
CPPFLAGS        = -I. -I$(TOPSRC)/include ${PARAM} -DKERNEL -DN64 -DMIPS \
                  -DHW_MACHINE_NAME=\"mips\" \
                  -DHW_MODEL_NAME='"NEC VR4300"'
ifneq ($(filter -DINET_ENABLED,$(PARAM)),)
CPPFLAGS        += -I$(TOPSRC)/include/sys -I$(TOPSRC)/sys \
                  -I$(TOPSRC)/sys/net \
                  -I$(TOPSRC)/sys/netinet -DINET -DSUPERVISOR
INET_CWARN      = -Wno-comment -Wno-endif-labels -Wno-implicit-int \
                  -Wno-implicit-function-declaration -Wno-parentheses \
                  -Wno-return-mismatch -Wno-return-type
endif
ifneq ($(filter -DUNIXDOMAIN_ENABLED,$(PARAM)),)
CPPFLAGS        += -DUNIXDOMAIN
endif
ifeq ($(N64_TRACE),1)
CPPFLAGS        += -DN64_TRACE
endif
CPPFLAGS        += -DROMFS_ENABLED
DEFS            = $(CPPFLAGS) $(DEPFLAGS)
CFLAGS          = -O2 -Wall -Werror -Wno-array-bounds -nostdinc $(DEFS) $(INET_CWARN)
VERS_CFLAGS     = -O2 -Wall -Werror -Wno-array-bounds -nostdinc $(CPPFLAGS)
ASFLAGS         = -x assembler-with-cpp -c $(DEFS)
FPU_ASFLAGS     = -x assembler-with-cpp -c $(DEFS)
STAGE0_CFLAGS   = $(N64_KERNEL_ARCH) $(N64_KERNEL_BASE) -msoft-float \
                  -ffreestanding -fno-builtin -fno-stack-protector \
                  -fno-pie -Wall -Wextra -Werror -O2 -MMD -MP $(PARAM)
STAGE0_ASFLAGS  = $(N64_KERNEL_ARCH) $(N64_KERNEL_BASE) -msoft-float \
                  -x assembler-with-cpp -MMD -MP -c $(PARAM)

COMPILE_C       = ${CC} ${CFLAGS} -c $<
COMPILE_S       = ${AS} ${ASFLAGS} $< -o $@
COMPILE_FPU_S   = ${ASFPU} ${FPU_ASFLAGS} $< -o $@

%OBJS

%CFILES

ifeq ($(N64_DEBUG_UART_ONLY),1)
OBJS := $(filter-out video.o video_console.o si.o joybus.o \
    n64usbnet_proto.o n64cart_usbnet.o n64cart_usbecm.o,$(OBJS))
CFILES := $(filter-out \
    $S/mips/n64/video.c \
    $S/mips/n64/video_console.c \
    $S/mips/n64/si.c \
    $S/mips/n64/joybus.c \
    $S/mips/common/n64usbnet_proto.c \
    $S/mips/n64/n64cart_usbnet.c \
    $S/mips/n64/n64cart_usbecm.c,$(CFILES))
endif

SYSTEM_OBJ      = startup.o ${OBJS} ioconf.o
SYSTEM_DEP      = Makefile ioconf.c $(N64_KERNEL_LDSCRIPT)
SYSTEM_LD_HEAD  = printf '%s\n' 'const char version[] = "ReBSD for N64: local build\n";' > vers.c; \
                  ${CC} ${VERS_CFLAGS} -MT vers.o -MP -MD -MF .deps/vers.dep -c vers.c -o vers.o; \
                  rm -f $@
SYSTEM_LD       = ${LD} -nostdlib -T $(N64_KERNEL_LDSCRIPT) ${SYSTEM_OBJ} vers.o -o $@
SYSTEM_LD_TAIL  = ${SIZE} $@; \
                  ${OBJDUMP} -d -S $@ > $(basename $@).dis; \
                  ${NM} -n $@ > $(basename $@).nm

all: unix kernel.z64 preflight.z64

%LOAD

preflight: $(N64_PREFLIGHT_OBJS)
	$(SIZE) $(N64_PREFLIGHT_OBJS)

$(N64_KERNEL_LDSCRIPT): n64.ld.S layout.h
	$(N64_PREFIX)gcc -E -P -undef -x c $< -o $@

$(N64_USER_LDSCRIPT): user/user.ld.S layout.h
	$(N64_PREFIX)gcc -E -P -undef -x c $< -o $@

preflight.elf: $(N64_PREFLIGHT_OBJS) $(N64_KERNEL_LDSCRIPT)
	$(LD) -nostdlib -T $(N64_KERNEL_LDSCRIPT) $(N64_PREFLIGHT_OBJS) -o $@
	$(SIZE) $@
	$(OBJDUMP) -d -S $@ > preflight.dis

stage0.o: stage0.S | .deps
	$(N64_PREFIX)gcc $(STAGE0_ASFLAGS) $< -o $@

stage0_loader.o: stage0_loader.c | .deps
	$(N64_PREFIX)gcc $(STAGE0_CFLAGS) -c $< -o $@

stage0_console_null.o: stage0_console_null.c stage0_console.h | .deps
	$(N64_PREFIX)gcc $(STAGE0_CFLAGS) -c $< -o $@

stage0_n64cart_uart.o: stage0_n64cart_uart.c stage0_console.h n64cart_uart.h | .deps
	$(N64_PREFIX)gcc $(STAGE0_CFLAGS) -c $< -o $@

stage0_kernel_blob.o: stage0_kernel_blob.S preflight.elf | .deps
	$(N64_PREFIX)gcc $(STAGE0_ASFLAGS) -DN64_KERNEL_ELF=\"$(abspath preflight.elf)\" $< -o $@

kernel_stage0_kernel_blob.o: stage0_kernel_blob.S unix.elf | .deps
	$(N64_PREFIX)gcc $(STAGE0_ASFLAGS) -DN64_KERNEL_ELF=\"$(abspath unix.elf)\" $< -o $@

stage0.elf: $(N64_STAGE0_OBJS) stage0_kernel_blob.o stage0_linker.ld
	$(LD) -T stage0_linker.ld -nostdlib -o $@ $(N64_STAGE0_OBJS) stage0_kernel_blob.o

kernel_stage0.elf: $(N64_STAGE0_OBJS) kernel_stage0_kernel_blob.o stage0_linker.ld
	$(LD) -T stage0_linker.ld -nostdlib -o $@ $(N64_STAGE0_OBJS) kernel_stage0_kernel_blob.o

stage0.stripped.elf: stage0.elf
	$(STRIP) -s -o $@ $<

kernel_stage0.stripped.elf: kernel_stage0.elf
	$(STRIP) -s -o $@ $<

$(N64_BUILD_MODE_STAMP):
	rm -f .build-mode.0 .build-mode.1
	touch $@

$(N64_ROOTFS_DEVNODES): $(N64_DEVNODES_SRCS) Makefile
	awk -v cons_major="$(N64_CONS_MAJOR)" -v cons_minor="$(N64_CONS_MINOR)" -v pty_enabled="$(N64_PTY_ENABLED)" -v pty_nunits="$(N64_PTY_NUNITS)" -f $(N64_DEVNODES_AWK) $(TOPSRC)/sys/mips/n64/romdisk.h $(TOPSRC)/sys/mips/n64/ramswap.h $(TOPSRC)/sys/mips/n64/devmajors.h $(TOPSRC)/sys/include/conf.h $(TOPSRC)/sys/include/pty.h > $@

$(N64_ROOTFS_BUILD_MANIFEST): $(N64_ROOTFS_MANIFEST) $(N64_ROOTFS_DEVNODES) $(N64_ROOTFS_USER_STAMP) $(N64_ROOTFS_EXTRA_STAMPS)
	cp $(N64_ROOTFS_MANIFEST) $@
	find $(N64_ROOTFS_USR_INCLUDE) -type d | sort | while read path; do \
	    rel=$${path#$(N64_ROOTFS_STAGE)}; \
	    printf '\ndir %s\n' "$$rel" >> $@; \
	done
	find $(N64_ROOTFS_USR_INCLUDE) -type f ! -name '.gitignore' \
	    ! -name Makefile ! -name Makefile.install | sort | while read path; do \
	    rel=$${path#$(N64_ROOTFS_STAGE)}; \
	    printf '\nfile %s\n' "$$rel" >> $@; \
	done
	find $(N64_ROOTFS_USR_INCLUDE) -maxdepth 1 -type l ! -name pic32 | \
	    sort | while read path; do \
	    rel=$${path#$(N64_ROOTFS_STAGE)}; \
	    target=$$(readlink "$$path"); \
	    printf '\nsymlink %s\ntarget %s\n' "$$rel" "$$target" >> $@; \
	done
	cat $(N64_ROOTFS_DEVNODES) >> $@
	if [ "$(N64_USERLAND_COMPILER)" = "pcc" ]; then \
	    printf '\nfile /root/linpack-gcc\nmode 0775\n' >> $@; \
	    printf '\nfile /root/linpack-pcc\nmode 0775\n' >> $@; \
	fi

$(N64_LINPACK_ROOTFS_STAMP): $(N64_ROOTFS_USER_STAMP) $(N64_HOST_PCC) \
    $(N64_NATIVE_AS) $(N64_NATIVE_LD) $(N64_LINPACK_SMOKE_SCRIPT) \
    $(N64_LINPACK_SMOKE_SRC)
	python3 $(N64_LINPACK_SMOKE_SCRIPT) build \
	    --source $(abspath $(N64_LINPACK_SMOKE_SRC)) \
	    --out $(N64_LINPACK_SMOKE_OUT) \
	    --top $(abspath $(TOPSRC)) \
	    --rootfs $(abspath $(N64_ROOTFS_STAGE)) \
	    --gcc-wrapper $(abspath $(N64_NATIVE_CC_SCRIPT)) \
	    --gcc-prefix $(N64_PREFIX) \
	    --as $(abspath $(N64_NATIVE_AS)) \
	    --ld $(abspath $(N64_NATIVE_LD)) \
	    --pcc $(abspath $(N64_HOST_PCC))
	cp -p $(N64_LINPACK_SMOKE_OUT)/linpack-gcc \
	    $(N64_ROOTFS_STAGE)/root/linpack-gcc
	cp -p $(N64_LINPACK_SMOKE_OUT)/linpack-pcc \
	    $(N64_ROOTFS_STAGE)/root/linpack-pcc
	chmod 0775 $(N64_ROOTFS_STAGE)/root/linpack-gcc \
	    $(N64_ROOTFS_STAGE)/root/linpack-pcc
	touch $@

$(N64_ROOTFS_BASE_STAMP): $(N64_ROOTFS_FILES) $(N64_ROOTFS_DIRS) \
    $(N64_TERMCAP) $(N64_INCLUDE_SRCS) $(N64_INCLUDE_LINKS) \
    $(N64_NATIVE_AS_SMOKE_SCRIPT) \
    $(N64_NATIVE_AS_MATRIX_SCRIPT)
	rm -rf $(N64_ROOTFS_STAGE)
	mkdir -p $(N64_ROOTFS_STAGE)
	cp -pR $(N64_ROOTFS_COMMON_DIR)/. $(N64_ROOTFS_STAGE)/
	cp -pR $(N64_ROOTFS_BOARD_DIR)/. $(N64_ROOTFS_STAGE)/
	cp -p $(N64_TERMCAP) $(N64_ROOTFS_STAGE)/etc/termcap
	mkdir -p $(N64_ROOTFS_USR_INCLUDE)
	cp -pR $(TOPSRC)/include/. $(N64_ROOTFS_USR_INCLUDE)/
	rm -rf $(N64_ROOTFS_USR_INCLUDE)/machine $(N64_ROOTFS_USR_INCLUDE)/sys
	cp -pR $(TOPSRC)/sys/include $(N64_ROOTFS_USR_INCLUDE)/sys
	mkdir -p $(N64_ROOTFS_USR_INCLUDE)/mips
	cp -p $(TOPSRC)/sys/mips/*.h $(N64_ROOTFS_USR_INCLUDE)/mips/
	mkdir -p $(N64_ROOTFS_USR_INCLUDE)/machine
	cp -p $(TOPSRC)/sys/mips/n64/*.h $(N64_ROOTFS_USR_INCLUDE)/machine/
	for header in $(N64_COMMON_MACHINE_HEADERS); do \
	    cp -p $(TOPSRC)/sys/mips/$$header.h \
	        $(N64_ROOTFS_USR_INCLUDE)/machine/$$header.h; \
	done
	cp -p $(TOPSRC)/sys/mips/include/machine/types.h $(N64_ROOTFS_USR_INCLUDE)/machine/types.h
	sed 's|#include "../cartflash.h"|#include <mips/cartflash.h>|' \
	    $(TOPSRC)/sys/mips/n64/n64cart_flash.h \
	    > $(N64_ROOTFS_USR_INCLUDE)/machine/n64cart_flash.h
	mkdir -p $(N64_ROOTFS_STAGE)/lib
	mkdir -p $(N64_ROOTFS_STAGE)/sbin
	mkdir -p $(N64_ROOTFS_STAGE)/bin
	mkdir -p $(N64_ROOTFS_STAGE)/libexec
	mkdir -p $(N64_ROOTFS_STAGE)/share/misc
	mkdir -p $(N64_ROOTFS_STAGE)/share/man/cat1
	mkdir -p $(N64_ROOTFS_STAGE)/share/man/cat5
	mkdir -p $(N64_ROOTFS_STAGE)/share/man/cat8
	mkdir -p $(N64_ROOTFS_USR_BIN)
	mkdir -p $(N64_ROOTFS_USR_LIB)
	mkdir -p $(N64_ROOTFS_USR_LIBEXEC)
	mkdir -p $(N64_ROOTFS_USR_SHARE)/misc
	mkdir -p $(N64_ROOTFS_USR_SHARE)/man/cat1
	mkdir -p $(N64_ROOTFS_USR_SHARE)/man/cat5
	mkdir -p $(N64_ROOTFS_USR_SHARE)/man/cat8
	cp -p $(N64_NATIVE_AS_SMOKE_SCRIPT) $(N64_ROOTFS_USR_BIN)/smoke-as-vr4300
	cp -p $(N64_NATIVE_AS_SMOKE_SCRIPT) $(N64_ROOTFS_USR_BIN)/smoke-as-vr4300.sh
	cp -p $(N64_NATIVE_AS_MATRIX_SCRIPT) $(N64_ROOTFS_USR_BIN)/matrix-as-vr4300
	cp -p $(N64_NATIVE_AS_MATRIX_SCRIPT) $(N64_ROOTFS_USR_BIN)/matrix-as-vr4300.sh
	chmod 0775 $(N64_ROOTFS_USR_BIN)/smoke-as-vr4300 \
	    $(N64_ROOTFS_USR_BIN)/smoke-as-vr4300.sh \
	    $(N64_ROOTFS_USR_BIN)/matrix-as-vr4300 \
	    $(N64_ROOTFS_USR_BIN)/matrix-as-vr4300.sh
	touch $@

$(N64_ROOTFS_USER_STAMP): $(N64_ROOTFS_BASE_STAMP) $(N64_USERLAND_STAMP) $(N64_NATIVE_STAMP) $(N64_NATIVE_PCC_STAMP) $(N64_MAKEWHATIS_SED) Makefile
	mkdir -p $(N64_ROOTFS_STAGE)/share/misc \
	    $(N64_ROOTFS_STAGE)/share/man/cat1 \
	    $(N64_ROOTFS_STAGE)/share/man/cat5 \
	    $(N64_ROOTFS_STAGE)/share/man/cat8
	$(N64_SRC_MAKE) install
	$(N64_AWK_MAKE) install
	mkdir -p $(N64_ROOTFS_USR_BIN) $(N64_ROOTFS_USR_LIB) \
	    $(N64_ROOTFS_USR_LIBEXEC) $(N64_ROOTFS_USR_SHARE)
	for bin in $(N64_USR_BIN_FILES); do \
	    if [ -e $(N64_ROOTFS_STAGE)/bin/$$bin ]; then \
	        mv -f $(N64_ROOTFS_STAGE)/bin/$$bin $(N64_ROOTFS_USR_BIN)/$$bin; \
	    fi; \
	done
	for file in $(N64_USR_LIBEXEC_FILES); do \
	    if [ -e $(N64_ROOTFS_STAGE)/libexec/$$file ]; then \
	        mv -f $(N64_ROOTFS_STAGE)/libexec/$$file $(N64_ROOTFS_USR_LIBEXEC)/$$file; \
	    fi; \
	done
	rm -f $(N64_ROOTFS_USR_BIN)/cc $(N64_ROOTFS_USR_BIN)/cpp \
	    $(N64_ROOTFS_USR_BIN)/pcc $(N64_ROOTFS_USR_BIN)/p++ \
	    $(N64_ROOTFS_USR_BIN)/lcc $(N64_ROOTFS_USR_BIN)/scc
	rm -f $(N64_ROOTFS_USR_LIBEXEC)/ccom $(N64_ROOTFS_USR_LIBEXEC)/lccom \
	    $(N64_ROOTFS_USR_LIBEXEC)/smallc $(N64_ROOTFS_USR_LIBEXEC)/smlrc
	rm -f $(N64_ROOTFS_USR_LIBEXEC)/pcc/cxxcom
	mkdir -p $(N64_ROOTFS_USR_LIBEXEC)/pcc
	cp -p $(N64_NATIVE_PCC_DIR)/cc $(N64_ROOTFS_USR_BIN)/cc
	cp -p $(N64_NATIVE_PCC_DIR)/cc $(N64_ROOTFS_USR_BIN)/pcc
	cp -p $(N64_NATIVE_PCC_DIR)/cc $(N64_ROOTFS_USR_BIN)/cpp
	cp -p $(N64_NATIVE_PCC_DIR)/cpp $(N64_ROOTFS_USR_LIBEXEC)/pcc/cpp
	cp -p $(N64_NATIVE_PCC_DIR)/ccom $(N64_ROOTFS_USR_LIBEXEC)/pcc/ccom
	if [ -d $(N64_ROOTFS_STAGE)/share ]; then \
	    cp -pR $(N64_ROOTFS_STAGE)/share/. $(N64_ROOTFS_USR_SHARE)/; \
	    rm -rf $(N64_ROOTFS_STAGE)/share; \
	fi
	mkdir -p $(N64_ROOTFS_USR_INCLUDE)/mips
	cp -p $(TOPSRC)/sys/mips/*.h $(N64_ROOTFS_USR_INCLUDE)/mips/
	for lib in $(N64_NATIVE_LIBS); do \
	    cp -p $(N64_NATIVE_DIR)/$$lib $(N64_ROOTFS_USR_LIB)/$$lib; \
	done
	for lib in libc.a libm.a libpcc.a; do \
	    $(N64_NATIVE_AOUT_RANLIB) $(N64_ROOTFS_USR_LIB)/$$lib; \
	done
	mkdir -p $(N64_ROOTFS_USR_SHARE)/man/cat1 \
	    $(N64_ROOTFS_USR_SHARE)/man/cat5 \
	    $(N64_ROOTFS_USR_SHARE)/man/cat8
	for page in $(N64_ROOTFS_CAT1_PAGES); do \
	    GROFF_NO_SGR=1 $(MANROFF) $(TOPSRC)/src/man/man1/$$page.1 > $(N64_ROOTFS_USR_SHARE)/man/cat1/$$page.0; \
	done
	for spec in $(N64_ROOTFS_CMD_CAT1_SOURCES); do \
	    dir=$${spec%:*}; page=$${spec#*:}; \
	    GROFF_NO_SGR=1 $(MANROFF) $(TOPSRC)/src/cmd/$$dir/$$page.1 > $(N64_ROOTFS_USR_SHARE)/man/cat1/$$page.0; \
	done
	for alias in $(N64_ROOTFS_CAT1_ALIASES); do \
	    dst=$${alias%:*}; src=$${alias#*:}; \
	    cp $(N64_ROOTFS_USR_SHARE)/man/cat1/$$src.0 $(N64_ROOTFS_USR_SHARE)/man/cat1/$$dst.0; \
	done
	for page in $(N64_ROOTFS_CAT8_PAGES); do \
	    GROFF_NO_SGR=1 $(MANROFF) $(TOPSRC)/src/man/man8/$$page.8 > $(N64_ROOTFS_USR_SHARE)/man/cat8/$$page.0; \
	done
	for alias in $(N64_ROOTFS_CAT8_ALIASES); do \
	    dst=$${alias%:*}; src=$${alias#*:}; \
	    if [ ! -e $(N64_ROOTFS_USR_SHARE)/man/cat8/$$dst.0 ] || \
	        ! cmp -s $(N64_ROOTFS_USR_SHARE)/man/cat8/$$src.0 $(N64_ROOTFS_USR_SHARE)/man/cat8/$$dst.0; then \
	        cp $(N64_ROOTFS_USR_SHARE)/man/cat8/$$src.0 $(N64_ROOTFS_USR_SHARE)/man/cat8/$$dst.0; \
	    fi; \
	done
	rm -f $(N64_ROOTFS_WHATIS).tmp
	touch $(N64_ROOTFS_WHATIS).tmp
	for file in `find $(N64_ROOTFS_USR_SHARE)/man/cat* -type f -name '*.0' -print`; do \
	    sed -n -f $(N64_MAKEWHATIS_SED) $$file >> $(N64_ROOTFS_WHATIS).tmp; \
	done
	sort -u $(N64_ROOTFS_WHATIS).tmp > $(N64_ROOTFS_WHATIS)
	rm -f $(N64_ROOTFS_WHATIS).tmp
	rm -f $(N64_ROOTFS_STAGE)/.userland.gcc \
	    $(N64_ROOTFS_STAGE)/.userland.pcc \
	    $(N64_ROOTFS_USER_COMPAT_STAMP)
	touch $@
	touch $(N64_ROOTFS_USER_COMPAT_STAMP)

$(N64_ROOTFS_USER_COMPAT_STAMP): $(N64_ROOTFS_USER_STAMP)
	touch $@

rootfs.img: $(FSUTIL) $(N64_ROOTFS_BUILD_MANIFEST) $(N64_ROOTFS_USER_STAMP)
	rm -f $@
	$(FSUTIL) --new --endian=big --size=$(N64_ROOTFS_KBYTES) --manifest=$(N64_ROOTFS_BUILD_MANIFEST) $@ $(N64_ROOTFS_STAGE)
	$(FSUTIL) --check $@

.PHONY: pcc-debug-stage pcc-debug-image pcc-hw-test-stage pcc-hw-test-image
$(N64_PCC_DEBUG_RUNNER_OBJ): $(N64_PCC_DEBUG_RUNNER_SRC) \
    $(N64_NATIVE_STAMP) $(N64_NATIVE_AS)
	N64_AOUT_TOPSRC=$(abspath $(TOPSRC)) \
	    N64_AOUT_AS=$(abspath $(N64_NATIVE_AS)) \
	    N64_PREFIX=$(N64_PREFIX) \
	    $(N64_NATIVE_CC) -O -fno-builtin -fno-stack-protector \
	    $(filter -DN64_DEBUG_USERMEM_4M,$(PARAM)) \
	    -c -o $@ $<

$(N64_PCC_DEBUG_RUNNER): $(N64_PCC_DEBUG_RUNNER_OBJ) \
    $(N64_NATIVE_LD) $(N64_NATIVE_DIR)/crt0.o \
    $(N64_NATIVE_DIR)/libc.a $(N64_NATIVE_DIR)/libpcc.a
	$(N64_NATIVE_LD) -X -d -e _start -o $@ \
	    $(N64_NATIVE_DIR)/crt0.o $(N64_PCC_DEBUG_RUNNER_OBJ) \
	    -L $(N64_NATIVE_DIR) -lc -lpcc

pcc-debug-stage: $(N64_ROOTFS_USER_STAMP) $(N64_PCC_DEBUG_ROOTFS_SCRIPT) \
    $(N64_PCC_DEBUG_RUNNER) $(N64_PCC_TEST_SRCS)
	python3 $(N64_PCC_DEBUG_ROOTFS_SCRIPT) \
	    --top $(abspath $(TOPSRC)) \
	    --src-rootfs $(abspath $(N64_ROOTFS_STAGE)) \
	    --out-rootfs $(abspath $(N64_PCC_DEBUG_ROOTFS_STAGE)) \
	    --manifest-out $(abspath $(N64_PCC_DEBUG_ROOTFS_MANIFEST)) \
	    --runner $(abspath $(N64_PCC_DEBUG_RUNNER))

$(N64_PCC_DEBUG_ROOTFS_IMG): $(FSUTIL) pcc-debug-stage
	rm -f $@
	$(FSUTIL) --new --endian=big --size=$(N64_PCC_DEBUG_ROOTFS_KBYTES) --manifest=$(N64_PCC_DEBUG_ROOTFS_MANIFEST) $@ $(N64_PCC_DEBUG_ROOTFS_STAGE)
	$(FSUTIL) --check $@

pcc-debug.z64: N64_DEBUG_UART_ONLY=1
pcc-debug.z64: kernel_stage0.stripped.elf $(N64_PCC_DEBUG_ROOTFS_IMG)
	cp $(N64_PCC_DEBUG_ROOTFS_IMG) $(N64_PCC_DEBUG_TOC_ROOTFS_IMG)
	$(N64_TOOL) --toc --title "REBSD PCCDBG" --output $@ --align 256 kernel_stage0.stripped.elf --align 1024 $(N64_PCC_DEBUG_TOC_ROOTFS_IMG)

pcc-debug-image:
	$(MAKE) clean
	$(MAKE) N64_DEBUG_UART_ONLY=1 N64_USERLAND_COMPILER=pcc \
	    N64_PCC_DEBUG_ROOTFS_KBYTES=$(N64_PCC_DEBUG_ROOTFS_KBYTES) \
	    pcc-debug.z64

pcc-hw-test-stage: $(N64_ROOTFS_BUILD_MANIFEST) $(N64_HOST_PCC) \
    $(N64_NATIVE_AS) $(N64_NATIVE_LD) $(N64_NATIVE_AOUT_AR) \
    $(N64_LINPACK_SMOKE_SCRIPT) $(N64_LINPACK_SMOKE_SRC) \
    $(N64_PCC_REGRESS_SCRIPT) $(N64_PCC_TEST_SRCS)
	python3 $(N64_LINPACK_SMOKE_SCRIPT) build \
	    --source $(abspath $(N64_LINPACK_SMOKE_SRC)) \
	    --out $(N64_LINPACK_SMOKE_OUT) \
	    --top $(abspath $(TOPSRC)) \
	    --rootfs $(abspath $(N64_ROOTFS_STAGE)) \
	    --gcc-wrapper $(abspath $(N64_NATIVE_CC_SCRIPT)) \
	    --gcc-prefix $(N64_PREFIX) \
	    --as $(abspath $(N64_NATIVE_AS)) \
	    --ld $(abspath $(N64_NATIVE_LD)) \
	    --pcc $(abspath $(N64_HOST_PCC))
	python3 $(N64_LINPACK_SMOKE_SCRIPT) stage \
	    --out $(N64_LINPACK_SMOKE_OUT) \
	    --rootfs $(abspath $(N64_ROOTFS_STAGE)) \
	    --manifest $(abspath $(N64_ROOTFS_BUILD_MANIFEST)) \
	    --manifest-out $(abspath $(N64_LINPACK_SMOKE_MANIFEST))
	python3 $(N64_PCC_REGRESS_SCRIPT) native-stage \
	    --rootfs $(abspath $(N64_ROOTFS_STAGE)) \
	    --manifest $(abspath $(N64_LINPACK_SMOKE_MANIFEST)) \
	    --manifest-out $(abspath $(N64_PCC_HW_REGRESS_MANIFEST))

pcc-hw-test-image: pcc-hw-test-stage
	rm -f rootfs.img kernel.z64 preflight.z64
	$(MAKE) N64_ROOTFS_BUILD_MANIFEST=$(N64_PCC_HW_REGRESS_MANIFEST) \
	    rootfs.img kernel.z64 preflight.z64

$(TOPSRC)/src/crt0.o: $(N64_CRT0_SRCS)
	$(N64_PREFIX)gcc $(N64_ARCH) $(N64_CODE) -x assembler-with-cpp -c $< -o $@

$(TOPSRC)/src/libc.a: $(TOPSRC)/src/crt0.o $(N64_LIBC_SRCS)
	$(N64_SRC_MAKE) libc

$(N64_USERLAND_STAMP): $(N64_USER_LDSCRIPT) $(TOPSRC)/src/crt0.o $(N64_CRT0_SRCS) $(N64_LIBC_SRCS) $(N64_LIBM_SRCS) $(N64_LIBUTIL_SRCS) $(N64_LIBTERMLIB_SRCS) $(N64_LIBCURSES_SRCS) $(N64_LIBVMF_SRCS) $(N64_LIBREADLINE_SRCS) $(N64_LIBTCL_SRCS) $(N64_USER_SRCS) $(N64_AWK_SRCS) $(N64_USERLAND_EXTRA_DEPS) Makefile
	$(N64_SRC_MAKE) clean
	$(N64_AWK_MAKE) clean
	$(MAKE) $(TOPSRC)/src/crt0.o
	$(N64_SRC_MAKE) -B all
	$(N64_AWK_MAKE) clean
	$(N64_AWK_MAKE) awk
	rm -f n64-userland.gcc.stamp n64-userland.pcc.stamp n64-userland.stamp
	touch $@

$(N64_NATIVE_HOST_INCLUDE_STAMP): $(N64_NATIVE_MKHOSTINCLUDE) \
    $(TOPSRC)/include/a.out.h $(TOPSRC)/include/ar.h \
    $(TOPSRC)/include/nlist.h $(TOPSRC)/include/ranlib.h \
    $(TOPSRC)/include/sys/exec_aout.h
	$(N64_NATIVE_MKHOSTINCLUDE) $(TOPSRC) $(N64_NATIVE_HOST_INCLUDE)
	touch $@

$(N64_NATIVE_AS): $(N64_NATIVE_HOST_INCLUDE_STAMP) \
    $(TOPSRC)/src/cmd/as/as.c $(TOPSRC)/src/cmd/aoutio.c \
    $(TOPSRC)/src/cmd/aoutio.h
	mkdir -p $(N64_NATIVE_TOOLS)
	cc -DCROSS $(N64_NATIVE_TARGET_FLAGS) \
	    -I$(N64_NATIVE_HOST_INCLUDE) -I$(TOPSRC)/src/cmd \
	    -o $@ $(TOPSRC)/src/cmd/as/as.c $(TOPSRC)/src/cmd/aoutio.c

$(N64_NATIVE_LD): $(N64_NATIVE_HOST_INCLUDE_STAMP) \
    $(TOPSRC)/src/cmd/ld/ld.c $(TOPSRC)/src/cmd/aoutio.c \
    $(TOPSRC)/src/cmd/aoutio.h
	mkdir -p $(N64_NATIVE_TOOLS)
	cc -DCROSS $(N64_NATIVE_TARGET_FLAGS) \
	    -I$(N64_NATIVE_HOST_INCLUDE) -I$(TOPSRC)/src/cmd \
	    -o $@ $(TOPSRC)/src/cmd/ld/ld.c $(TOPSRC)/src/cmd/aoutio.c

$(N64_NATIVE_AOUT_AR): $(N64_NATIVE_HOST_INCLUDE_STAMP) \
    $(TOPSRC)/src/cmd/ar/append.c $(TOPSRC)/src/cmd/ar/ar.c \
    $(TOPSRC)/src/cmd/ar/archive.c $(TOPSRC)/src/cmd/ar/contents.c \
    $(TOPSRC)/src/cmd/ar/delete.c $(TOPSRC)/src/cmd/ar/extract.c \
    $(TOPSRC)/src/cmd/ar/extern.h $(TOPSRC)/src/cmd/ar/misc.c \
    $(TOPSRC)/src/cmd/ar/move.c $(TOPSRC)/src/cmd/ar/print.c \
    $(TOPSRC)/src/cmd/ar/replace.c $(TOPSRC)/src/cmd/ar/strmode.c
	mkdir -p $(N64_NATIVE_TOOLS)
	cc -DCROSS $(N64_NATIVE_TARGET_FLAGS) \
	    -I$(N64_NATIVE_HOST_INCLUDE) -I$(TOPSRC)/src/cmd \
	    -I$(TOPSRC)/src/cmd/ar \
	    -o $@ \
	    $(TOPSRC)/src/cmd/ar/append.c \
	    $(TOPSRC)/src/cmd/ar/ar.c \
	    $(TOPSRC)/src/cmd/ar/archive.c \
	    $(TOPSRC)/src/cmd/ar/contents.c \
	    $(TOPSRC)/src/cmd/ar/delete.c \
	    $(TOPSRC)/src/cmd/ar/extract.c \
	    $(TOPSRC)/src/cmd/ar/misc.c \
	    $(TOPSRC)/src/cmd/ar/move.c \
	    $(TOPSRC)/src/cmd/ar/print.c \
	    $(TOPSRC)/src/cmd/ar/replace.c \
	    $(TOPSRC)/src/cmd/ar/strmode.c

$(N64_NATIVE_AOUT_RANLIB): $(N64_NATIVE_HOST_INCLUDE_STAMP) \
    $(TOPSRC)/src/cmd/ranlib/ranlib.c $(TOPSRC)/src/cmd/ar/archive.c \
    $(TOPSRC)/src/cmd/aoutio.c $(TOPSRC)/src/cmd/aoutio.h
	mkdir -p $(N64_NATIVE_TOOLS)
	cc -DCROSS $(N64_NATIVE_TARGET_FLAGS) \
	    -I$(N64_NATIVE_HOST_INCLUDE) -I$(TOPSRC)/src/cmd \
	    -I$(TOPSRC)/src/cmd/ar \
	    -o $@ $(TOPSRC)/src/cmd/ranlib/ranlib.c \
	    $(TOPSRC)/src/cmd/ar/archive.c $(TOPSRC)/src/cmd/aoutio.c

$(N64_NATIVE_AOUT_NM): $(N64_NATIVE_HOST_INCLUDE_STAMP) \
    $(TOPSRC)/src/cmd/nm/nm.c $(TOPSRC)/src/cmd/aoutio.c \
    $(TOPSRC)/src/cmd/aoutio.h
	mkdir -p $(N64_NATIVE_TOOLS)
	cc -DCROSS $(N64_NATIVE_TARGET_FLAGS) \
	    -I$(N64_NATIVE_HOST_INCLUDE) -I$(TOPSRC)/src/cmd \
	    -I$(TOPSRC)/src/cmd/ar \
	    -o $@ $(TOPSRC)/src/cmd/nm/nm.c $(TOPSRC)/src/cmd/aoutio.c

$(N64_NATIVE_AOUT_SIZE): $(N64_NATIVE_HOST_INCLUDE_STAMP) \
    $(TOPSRC)/src/cmd/size.c $(TOPSRC)/src/cmd/aoutio.c \
    $(TOPSRC)/src/cmd/aoutio.h
	mkdir -p $(N64_NATIVE_TOOLS)
	cc $(N64_NATIVE_TARGET_FLAGS) \
	    -I$(N64_NATIVE_HOST_INCLUDE) -I$(TOPSRC)/src/cmd \
	    -o $@ $(TOPSRC)/src/cmd/size.c $(TOPSRC)/src/cmd/aoutio.c

$(N64_NATIVE_AOUT_STRIP): $(N64_NATIVE_HOST_INCLUDE_STAMP) \
    $(TOPSRC)/src/cmd/strip.c $(TOPSRC)/src/cmd/aoutio.c \
    $(TOPSRC)/src/cmd/aoutio.h
	mkdir -p $(N64_NATIVE_TOOLS)
	cc $(N64_NATIVE_TARGET_FLAGS) \
	    -I$(N64_NATIVE_HOST_INCLUDE) -I$(TOPSRC)/src/cmd \
	    -o $@ $(TOPSRC)/src/cmd/strip.c $(TOPSRC)/src/cmd/aoutio.c

$(N64_HOST_CCOM): $(N64_HOST_CCOM_BUILD_SCRIPT) $(N64_CCOM_SRCS)
	sh $(N64_HOST_CCOM_BUILD_SCRIPT) $(TOPSRC) $(N64_HOST_CCOM_BUILD) $@

$(N64_HOST_CPP): $(N64_HOST_CPP_BUILD_SCRIPT) $(N64_CPP_SRCS)
	sh $(N64_HOST_CPP_BUILD_SCRIPT) $(TOPSRC) $(N64_HOST_CPP_BUILD) $@

$(N64_HOST_PCC): $(N64_HOST_PORTABLECC_SCRIPT) $(N64_DEV_PCC_SRCS) \
    $(N64_ROOTFS_BASE_STAMP) $(N64_NATIVE_STAMP) $(N64_NATIVE_AS) $(N64_NATIVE_LD)
	sh $(N64_HOST_PORTABLECC_SCRIPT) $(abspath $(TOPSRC)) \
	    $(abspath $(N64_PCC_HOST_BUILD)) \
	    $(abspath $(N64_PCC_HOST_PREFIX)) \
	    $(abspath $(N64_ROOTFS_USR_INCLUDE)) \
	    $(abspath $(N64_NATIVE_DIR)) \
	    $(abspath $(N64_NATIVE_AS)) $(abspath $(N64_NATIVE_LD))

.PHONY: smoke-as-vr4300
smoke-as-vr4300: $(N64_NATIVE_AS) $(N64_NATIVE_AS_SMOKE_SCRIPT)
	$(N64_NATIVE_AS_SMOKE_SCRIPT) $(abspath $(N64_NATIVE_AS))

.PHONY: matrix-as-vr4300
matrix-as-vr4300: $(N64_NATIVE_AS) $(N64_NATIVE_AS_MATRIX_SCRIPT)
	$(N64_NATIVE_AS_MATRIX_SCRIPT) $(abspath $(N64_NATIVE_AS)) $(N64_GNU_AS)

.PHONY: smoke-aout-toolchain
smoke-aout-toolchain: $(N64_NATIVE_AS) $(N64_NATIVE_LD) \
    $(N64_NATIVE_AOUT_AR) $(N64_NATIVE_AOUT_RANLIB) \
    $(N64_NATIVE_AOUT_NM) $(N64_NATIVE_AOUT_SIZE) $(N64_NATIVE_AOUT_STRIP) \
    $(N64_NATIVE_AOUT_SMOKE_SCRIPT)
	$(N64_NATIVE_AOUT_SMOKE_SCRIPT) $(abspath $(N64_NATIVE_AS)) \
	    $(abspath $(N64_NATIVE_LD)) $(abspath $(N64_NATIVE_AOUT_AR)) \
	    $(abspath $(N64_NATIVE_AOUT_RANLIB)) $(abspath $(N64_NATIVE_AOUT_NM)) \
	    $(abspath $(N64_NATIVE_AOUT_SIZE)) $(abspath $(N64_NATIVE_AOUT_STRIP)) \
	    $(N64_GNU_AS)

.PHONY: smoke-host-pcc smoke-host-ccom
smoke-host-pcc: $(N64_HOST_CPP) $(N64_HOST_CCOM) $(N64_NATIVE_AS) \
    $(N64_NATIVE_LD) $(N64_HOST_PCC_SMOKE_SCRIPT) \
    $(TOPSRC)/sys/mips/rootfs/root/types-smoke.c \
    $(TOPSRC)/sys/mips/rootfs/root/ll-smoke.c \
    $(TOPSRC)/sys/mips/rootfs/root/ll-abi-smoke.c
	sh $(N64_HOST_PCC_SMOKE_SCRIPT) $(abspath $(N64_HOST_CPP)) \
	    $(abspath $(N64_HOST_CCOM)) $(abspath $(N64_NATIVE_AS)) \
	    $(abspath $(N64_NATIVE_LD)) $(abspath $(TOPSRC)/include) \
	    $(TOPSRC)/sys/mips/rootfs/root/types-smoke.c
	sh $(N64_HOST_PCC_SMOKE_SCRIPT) $(abspath $(N64_HOST_CPP)) \
	    $(abspath $(N64_HOST_CCOM)) $(abspath $(N64_NATIVE_AS)) \
	    $(abspath $(N64_NATIVE_LD)) $(abspath $(TOPSRC)/include) \
	    $(TOPSRC)/sys/mips/rootfs/root/ll-smoke.c
	sh $(N64_HOST_PCC_SMOKE_SCRIPT) $(abspath $(N64_HOST_CPP)) \
	    $(abspath $(N64_HOST_CCOM)) $(abspath $(N64_NATIVE_AS)) \
	    $(abspath $(N64_NATIVE_LD)) $(abspath $(TOPSRC)/include) \
	    $(TOPSRC)/sys/mips/rootfs/root/ll-abi-smoke.c

smoke-host-ccom: smoke-host-pcc

$(N64_NATIVE_DIR)/crt0.o: $(N64_NATIVE_AS) $(N64_NATIVE_CRT0_SRC)
	mkdir -p $(N64_NATIVE_DIR)
	$(N64_NATIVE_AS) -EB -mips3 -march=vr4300 -o $@ $(N64_NATIVE_CRT0_SRC)

$(N64_NATIVE_STAMP): $(N64_NATIVE_RUNTIME_SRCS) $(N64_NATIVE_AS) $(N64_NATIVE_LD) \
    $(N64_NATIVE_DIR)/crt0.o $(N64_NATIVE_AOUT_AR) $(N64_NATIVE_AOUT_RANLIB)
	rm -rf $(N64_NATIVE_TREE)
	mkdir -p $(N64_NATIVE_TREE)/src $(N64_NATIVE_TREE)/sys/mips/n64
	cp -pR $(TOPSRC)/include $(N64_NATIVE_TREE)/
	cp -pR $(TOPSRC)/sys/include $(N64_NATIVE_TREE)/sys/
	cp -p $(TOPSRC)/sys/mips/*.h $(N64_NATIVE_TREE)/sys/mips/
	cp -p $(TOPSRC)/sys/mips/n64/*.h $(N64_NATIVE_TREE)/sys/mips/n64/
	cp -pR $(TOPSRC)/sys/mips/n64/include $(N64_NATIVE_TREE)/sys/mips/n64/
	cp -pR $(TOPSRC)/src/libc $(TOPSRC)/src/libm $(N64_NATIVE_TREE)/src/
	cp -p $(TOPSRC)/target.mk $(TOPSRC)/target-n64.mk $(N64_NATIVE_TREE)/
	N64_AOUT_TOPSRC=$(abspath $(N64_NATIVE_TREE)) \
	    N64_AOUT_AS=$(abspath $(N64_NATIVE_AS)) \
	    N64_PREFIX=$(N64_PREFIX) \
	    $(MAKE) -C $(N64_NATIVE_TREE)/src/libc TARGET_PLATFORM=n64 \
	    CC="$(N64_NATIVE_CC)" AS="$(N64_NATIVE_ASWRAP)" \
	    AR=$(abspath $(N64_NATIVE_AOUT_AR)) \
	    RANLIB=$(abspath $(N64_NATIVE_AOUT_RANLIB)) clean all
	$(N64_NATIVE_AOUT_RANLIB) $(N64_NATIVE_TREE)/src/libc.a
	N64_AOUT_TOPSRC=$(abspath $(N64_NATIVE_TREE)) \
	    N64_AOUT_AS=$(abspath $(N64_NATIVE_AS)) \
	    N64_PREFIX=$(N64_PREFIX) \
	    $(MAKE) -C $(N64_NATIVE_TREE)/src/libm TARGET_PLATFORM=n64 \
	    CC="$(N64_NATIVE_CC)" AS="$(N64_NATIVE_ASWRAP)" \
	    AR=$(abspath $(N64_NATIVE_AOUT_AR)) \
	    RANLIB=$(abspath $(N64_NATIVE_AOUT_RANLIB)) clean all
	rm -rf $(N64_NATIVE_DIR)/libpcc-build
	mkdir -p $(N64_NATIVE_DIR)/libpcc-build
	set -e; for obj in $(N64_LIBPCC_OBJS); do \
	    src=$(abspath $(N64_LIBPCC_DIR))/$${obj%.o}.c; \
	    N64_AOUT_TOPSRC=$(abspath $(N64_NATIVE_TREE)) \
	        N64_AOUT_AS=$(abspath $(N64_NATIVE_AS)) \
	        N64_PREFIX=$(N64_PREFIX) \
	        $(N64_NATIVE_CC) -O -fno-builtin -fno-stack-protector \
	        -DTARGET_BIG_ENDIAN=1 -Dos_rebsd -Dmach_mips \
	        -I$(abspath $(N64_LIBPCC_DIR)) \
	        -I$(abspath $(N64_LIBPCC_DIR))/include \
	        -c -o $(N64_NATIVE_DIR)/libpcc-build/$$obj $$src; \
	done
	rm -f $(N64_NATIVE_DIR)/libpcc.a
	cd $(N64_NATIVE_DIR)/libpcc-build && \
	    $(abspath $(N64_NATIVE_AOUT_AR)) r ../libpcc.a $(N64_LIBPCC_OBJS)
	$(N64_NATIVE_AOUT_RANLIB) $(N64_NATIVE_DIR)/libpcc.a
	cp $(N64_NATIVE_TREE)/src/libc.a $(N64_NATIVE_DIR)/libc.a
	cp $(N64_NATIVE_TREE)/src/libm.a $(N64_NATIVE_DIR)/libm.a
	touch $@

$(N64_NATIVE_PCC_STAMP): $(N64_DEV_PCC_SRCS) $(N64_NATIVE_STAMP) \
    $(N64_NATIVE_AS) $(N64_NATIVE_LD) $(N64_NATIVE_DIR)/crt0.o \
    $(N64_NATIVE_DIR)/libc.a $(N64_NATIVE_DIR)/libm.a \
    $(N64_NATIVE_DIR)/libpcc.a Makefile
	python3 $(N64_NATIVE_PCC_BUILD_SCRIPT) \
	    --top $(abspath $(TOPSRC)) \
	    --build $(abspath $(N64_NATIVE_PCC_BUILD)) \
	    --out $(abspath $(N64_NATIVE_PCC_DIR)) \
	    --gcc-wrapper $(abspath $(N64_NATIVE_CC_SCRIPT)) \
	    --gcc-prefix $(N64_PREFIX) \
	    --as $(abspath $(N64_NATIVE_AS)) \
	    --ld $(abspath $(N64_NATIVE_LD)) \
	    --crt0 $(abspath $(N64_NATIVE_DIR)/crt0.o) \
	    --libdir $(abspath $(N64_NATIVE_DIR)) \
	    --bison $(N64_BISON)
	touch $@

$(FSUTIL):
	$(MAKE) -C $(TOPSRC)/tools/fsutil

$(ELF2AOUT): $(ELF2AOUT_SRCS)
	$(MAKE) -C $(TOPSRC)/tools/elf2aout

preflight.z64: stage0.stripped.elf rootfs.img
	$(N64_TOOL) --toc --title "REBSD N64" --output $@ --align 256 stage0.stripped.elf --align 1024 rootfs.img

kernel.z64: kernel_stage0.stripped.elf rootfs.img
	$(N64_TOOL) --toc --title "REBSD N64" --output $@ --align 256 kernel_stage0.stripped.elf --align 1024 rootfs.img

preflight.o: preflight.c ${SYSTEM_DEP}
	${COMPILE_C}

preflight_n64cart_uart.o: preflight_n64cart_uart.c n64cart_uart.h ${SYSTEM_DEP}
	${COMPILE_C}

startup.o: $S/mips/common/startup.S ${SYSTEM_DEP}
	${COMPILE_S}

ioconf.o: ioconf.c ${SYSTEM_DEP}
	${COMPILE_C}

${SYSTEM_OBJ} swapunix.o preflight.o: | machine sys .deps
${SYSTEM_OBJ} swapunix.o preflight.o $(N64_STAGE0_OBJS) \
    $(N64_PREFLIGHT_OBJS): $(N64_BUILD_MODE_STAMP)

clean:
	$(N64_SRC_MAKE) clean
	$(N64_AWK_MAKE) clean
	rm -rf *.o *.elf *.bin *.img *.dis *.nm *.z64 *.d a.out n64-init \
	    .deps machine sys $(N64_ROOTFS_STAGE) $(N64_ROOTFS_DEVNODES) \
	    $(N64_ROOTFS_BUILD_MANIFEST) $(N64_PCC_DEBUG_ROOTFS_STAGE) \
	    $(N64_PCC_DEBUG_ROOTFS_MANIFEST) $(N64_KERNEL_LDSCRIPT) \
	    $(N64_USER_LDSCRIPT) n64-userland*.stamp .build-mode.* \
	    $(N64_PCC_DEBUG_RUNNER) $(N64_NATIVE_DIR) $(N64_NATIVE_TOOLS) \
	    $(N64_NATIVE_PCC_BUILD) $(N64_NATIVE_PCC_DIR)

clean-all: clean
	rm -f Makefile ioconf.c swap*.c vers.c

reconfig ioconf.c swapunix.c: Config ../../../tools/kconfig/kconfig | machine sys
	../../../tools/kconfig/kconfig Config

machine:
	ln -s . $@

sys:
	ln -s ../../include $@

.deps:
	mkdir .deps

%RULES

-include .deps/*.dep
